project_name: monkey
builds:
- env:
  - CGO_ENABLED=0
  - GRPCHOST=api.fuzzymonkey.co:7077
  goos:
  - darwin
  # TODO: - freebsd openbsd netbsd dragonfly
  - linux
  - windows
  goarch:
  - 386
  - amd64
  # TODO: - arm arm64
  # TODO: goarm: [6, 7]
  ignore: []
  ldflags: >
    -s
    -w
    -extldflags "-static"
    -X main.binVersion={{.Env.CURRENT_TAG}}
    -X github.com/FuzzyMonkeyCo/monkey/pkg/internal/fm.grpcHost={{.Env.GRPCHOST}}

archives:
- format_overrides:
  - goos: windows
    format: zip
    # uname -m + uname -s compatible
    # TODO: arm64: aarch64
  name_template: >-
    {{ .ProjectName }}-
    {{- title .Os }}-
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
  files:
  - LICENSE
  - README.md

checksum:
  name_template: checksums.sha256.txt
  algorithm: sha256

signs:
- artifacts: none

# TODO: homebrew
# TODO: snap
# TODO: apt
