// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package main

func (cmd *doneCmd) isMsg_Msg() {}

func (cmd *reqCmd) isMsg_Msg() {}

func (cmd *rstCmd) isMsg_Msg() {}

// func (cmd *RepCmdReset) isMsg_Msg() {}
