// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data_json.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JSON struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JSON) Reset()         { *m = JSON{} }
func (m *JSON) String() string { return proto.CompactTextString(m) }
func (*JSON) ProtoMessage()    {}
func (*JSON) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_json_e0526081189d52e2, []int{0}
}
func (m *JSON) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSON.Unmarshal(m, b)
}
func (m *JSON) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSON.Marshal(b, m, deterministic)
}
func (dst *JSON) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSON.Merge(dst, src)
}
func (m *JSON) XXX_Size() int {
	return xxx_messageInfo_JSON.Size(m)
}
func (m *JSON) XXX_DiscardUnknown() {
	xxx_messageInfo_JSON.DiscardUnknown(m)
}

var xxx_messageInfo_JSON proto.InternalMessageInfo

type JSON_Object struct {
	Object               map[string]*JSON_Value `protobuf:"bytes,1,rep,name=object,proto3" json:"object,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IsObject             bool                   `protobuf:"varint,2,opt,name=is_object,json=isObject,proto3" json:"is_object,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *JSON_Object) Reset()         { *m = JSON_Object{} }
func (m *JSON_Object) String() string { return proto.CompactTextString(m) }
func (*JSON_Object) ProtoMessage()    {}
func (*JSON_Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_json_e0526081189d52e2, []int{0, 0}
}
func (m *JSON_Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSON_Object.Unmarshal(m, b)
}
func (m *JSON_Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSON_Object.Marshal(b, m, deterministic)
}
func (dst *JSON_Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSON_Object.Merge(dst, src)
}
func (m *JSON_Object) XXX_Size() int {
	return xxx_messageInfo_JSON_Object.Size(m)
}
func (m *JSON_Object) XXX_DiscardUnknown() {
	xxx_messageInfo_JSON_Object.DiscardUnknown(m)
}

var xxx_messageInfo_JSON_Object proto.InternalMessageInfo

func (m *JSON_Object) GetObject() map[string]*JSON_Value {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *JSON_Object) GetIsObject() bool {
	if m != nil {
		return m.IsObject
	}
	return false
}

type JSON_Array struct {
	Array                []*JSON_Value `protobuf:"bytes,1,rep,name=array,proto3" json:"array,omitempty"`
	IsArray              bool          `protobuf:"varint,2,opt,name=is_array,json=isArray,proto3" json:"is_array,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *JSON_Array) Reset()         { *m = JSON_Array{} }
func (m *JSON_Array) String() string { return proto.CompactTextString(m) }
func (*JSON_Array) ProtoMessage()    {}
func (*JSON_Array) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_json_e0526081189d52e2, []int{0, 1}
}
func (m *JSON_Array) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSON_Array.Unmarshal(m, b)
}
func (m *JSON_Array) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSON_Array.Marshal(b, m, deterministic)
}
func (dst *JSON_Array) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSON_Array.Merge(dst, src)
}
func (m *JSON_Array) XXX_Size() int {
	return xxx_messageInfo_JSON_Array.Size(m)
}
func (m *JSON_Array) XXX_DiscardUnknown() {
	xxx_messageInfo_JSON_Array.DiscardUnknown(m)
}

var xxx_messageInfo_JSON_Array proto.InternalMessageInfo

func (m *JSON_Array) GetArray() []*JSON_Value {
	if m != nil {
		return m.Array
	}
	return nil
}

func (m *JSON_Array) GetIsArray() bool {
	if m != nil {
		return m.IsArray
	}
	return false
}

type JSON_Text struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IsText               bool     `protobuf:"varint,2,opt,name=is_text,json=isText,proto3" json:"is_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JSON_Text) Reset()         { *m = JSON_Text{} }
func (m *JSON_Text) String() string { return proto.CompactTextString(m) }
func (*JSON_Text) ProtoMessage()    {}
func (*JSON_Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_json_e0526081189d52e2, []int{0, 2}
}
func (m *JSON_Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSON_Text.Unmarshal(m, b)
}
func (m *JSON_Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSON_Text.Marshal(b, m, deterministic)
}
func (dst *JSON_Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSON_Text.Merge(dst, src)
}
func (m *JSON_Text) XXX_Size() int {
	return xxx_messageInfo_JSON_Text.Size(m)
}
func (m *JSON_Text) XXX_DiscardUnknown() {
	xxx_messageInfo_JSON_Text.DiscardUnknown(m)
}

var xxx_messageInfo_JSON_Text proto.InternalMessageInfo

func (m *JSON_Text) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *JSON_Text) GetIsText() bool {
	if m != nil {
		return m.IsText
	}
	return false
}

type JSON_Number struct {
	Number               float64  `protobuf:"fixed64,1,opt,name=number,proto3" json:"number,omitempty"`
	IsNumber             bool     `protobuf:"varint,2,opt,name=is_number,json=isNumber,proto3" json:"is_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JSON_Number) Reset()         { *m = JSON_Number{} }
func (m *JSON_Number) String() string { return proto.CompactTextString(m) }
func (*JSON_Number) ProtoMessage()    {}
func (*JSON_Number) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_json_e0526081189d52e2, []int{0, 3}
}
func (m *JSON_Number) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSON_Number.Unmarshal(m, b)
}
func (m *JSON_Number) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSON_Number.Marshal(b, m, deterministic)
}
func (dst *JSON_Number) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSON_Number.Merge(dst, src)
}
func (m *JSON_Number) XXX_Size() int {
	return xxx_messageInfo_JSON_Number.Size(m)
}
func (m *JSON_Number) XXX_DiscardUnknown() {
	xxx_messageInfo_JSON_Number.DiscardUnknown(m)
}

var xxx_messageInfo_JSON_Number proto.InternalMessageInfo

func (m *JSON_Number) GetNumber() float64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *JSON_Number) GetIsNumber() bool {
	if m != nil {
		return m.IsNumber
	}
	return false
}

type JSON_Boolean struct {
	Boolean              bool     `protobuf:"varint,1,opt,name=boolean,proto3" json:"boolean,omitempty"`
	IsBoolean            bool     `protobuf:"varint,2,opt,name=is_boolean,json=isBoolean,proto3" json:"is_boolean,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JSON_Boolean) Reset()         { *m = JSON_Boolean{} }
func (m *JSON_Boolean) String() string { return proto.CompactTextString(m) }
func (*JSON_Boolean) ProtoMessage()    {}
func (*JSON_Boolean) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_json_e0526081189d52e2, []int{0, 4}
}
func (m *JSON_Boolean) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSON_Boolean.Unmarshal(m, b)
}
func (m *JSON_Boolean) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSON_Boolean.Marshal(b, m, deterministic)
}
func (dst *JSON_Boolean) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSON_Boolean.Merge(dst, src)
}
func (m *JSON_Boolean) XXX_Size() int {
	return xxx_messageInfo_JSON_Boolean.Size(m)
}
func (m *JSON_Boolean) XXX_DiscardUnknown() {
	xxx_messageInfo_JSON_Boolean.DiscardUnknown(m)
}

var xxx_messageInfo_JSON_Boolean proto.InternalMessageInfo

func (m *JSON_Boolean) GetBoolean() bool {
	if m != nil {
		return m.Boolean
	}
	return false
}

func (m *JSON_Boolean) GetIsBoolean() bool {
	if m != nil {
		return m.IsBoolean
	}
	return false
}

type JSON_Null struct {
	IsNull               bool     `protobuf:"varint,1,opt,name=is_null,json=isNull,proto3" json:"is_null,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JSON_Null) Reset()         { *m = JSON_Null{} }
func (m *JSON_Null) String() string { return proto.CompactTextString(m) }
func (*JSON_Null) ProtoMessage()    {}
func (*JSON_Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_json_e0526081189d52e2, []int{0, 5}
}
func (m *JSON_Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSON_Null.Unmarshal(m, b)
}
func (m *JSON_Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSON_Null.Marshal(b, m, deterministic)
}
func (dst *JSON_Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSON_Null.Merge(dst, src)
}
func (m *JSON_Null) XXX_Size() int {
	return xxx_messageInfo_JSON_Null.Size(m)
}
func (m *JSON_Null) XXX_DiscardUnknown() {
	xxx_messageInfo_JSON_Null.DiscardUnknown(m)
}

var xxx_messageInfo_JSON_Null proto.InternalMessageInfo

func (m *JSON_Null) GetIsNull() bool {
	if m != nil {
		return m.IsNull
	}
	return false
}

type JSON_Value struct {
	// Types that are valid to be assigned to Value:
	//	*JSON_Value_Z
	//	*JSON_Value_B
	//	*JSON_Value_N
	//	*JSON_Value_T
	//	*JSON_Value_A
	//	*JSON_Value_O
	Value                isJSON_Value_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *JSON_Value) Reset()         { *m = JSON_Value{} }
func (m *JSON_Value) String() string { return proto.CompactTextString(m) }
func (*JSON_Value) ProtoMessage()    {}
func (*JSON_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_json_e0526081189d52e2, []int{0, 6}
}
func (m *JSON_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSON_Value.Unmarshal(m, b)
}
func (m *JSON_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSON_Value.Marshal(b, m, deterministic)
}
func (dst *JSON_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSON_Value.Merge(dst, src)
}
func (m *JSON_Value) XXX_Size() int {
	return xxx_messageInfo_JSON_Value.Size(m)
}
func (m *JSON_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_JSON_Value.DiscardUnknown(m)
}

var xxx_messageInfo_JSON_Value proto.InternalMessageInfo

type isJSON_Value_Value interface {
	isJSON_Value_Value()
}

type JSON_Value_Z struct {
	Z *JSON_Null `protobuf:"bytes,1,opt,name=z,proto3,oneof"`
}
type JSON_Value_B struct {
	B *JSON_Boolean `protobuf:"bytes,2,opt,name=b,proto3,oneof"`
}
type JSON_Value_N struct {
	N *JSON_Number `protobuf:"bytes,3,opt,name=n,proto3,oneof"`
}
type JSON_Value_T struct {
	T *JSON_Text `protobuf:"bytes,4,opt,name=t,proto3,oneof"`
}
type JSON_Value_A struct {
	A *JSON_Array `protobuf:"bytes,5,opt,name=a,proto3,oneof"`
}
type JSON_Value_O struct {
	O *JSON_Object `protobuf:"bytes,6,opt,name=o,proto3,oneof"`
}

func (*JSON_Value_Z) isJSON_Value_Value() {}
func (*JSON_Value_B) isJSON_Value_Value() {}
func (*JSON_Value_N) isJSON_Value_Value() {}
func (*JSON_Value_T) isJSON_Value_Value() {}
func (*JSON_Value_A) isJSON_Value_Value() {}
func (*JSON_Value_O) isJSON_Value_Value() {}

func (m *JSON_Value) GetValue() isJSON_Value_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *JSON_Value) GetZ() *JSON_Null {
	if x, ok := m.GetValue().(*JSON_Value_Z); ok {
		return x.Z
	}
	return nil
}

func (m *JSON_Value) GetB() *JSON_Boolean {
	if x, ok := m.GetValue().(*JSON_Value_B); ok {
		return x.B
	}
	return nil
}

func (m *JSON_Value) GetN() *JSON_Number {
	if x, ok := m.GetValue().(*JSON_Value_N); ok {
		return x.N
	}
	return nil
}

func (m *JSON_Value) GetT() *JSON_Text {
	if x, ok := m.GetValue().(*JSON_Value_T); ok {
		return x.T
	}
	return nil
}

func (m *JSON_Value) GetA() *JSON_Array {
	if x, ok := m.GetValue().(*JSON_Value_A); ok {
		return x.A
	}
	return nil
}

func (m *JSON_Value) GetO() *JSON_Object {
	if x, ok := m.GetValue().(*JSON_Value_O); ok {
		return x.O
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*JSON_Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _JSON_Value_OneofMarshaler, _JSON_Value_OneofUnmarshaler, _JSON_Value_OneofSizer, []interface{}{
		(*JSON_Value_Z)(nil),
		(*JSON_Value_B)(nil),
		(*JSON_Value_N)(nil),
		(*JSON_Value_T)(nil),
		(*JSON_Value_A)(nil),
		(*JSON_Value_O)(nil),
	}
}

func _JSON_Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*JSON_Value)
	// value
	switch x := m.Value.(type) {
	case *JSON_Value_Z:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Z); err != nil {
			return err
		}
	case *JSON_Value_B:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.B); err != nil {
			return err
		}
	case *JSON_Value_N:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.N); err != nil {
			return err
		}
	case *JSON_Value_T:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.T); err != nil {
			return err
		}
	case *JSON_Value_A:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.A); err != nil {
			return err
		}
	case *JSON_Value_O:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.O); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("JSON_Value.Value has unexpected type %T", x)
	}
	return nil
}

func _JSON_Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*JSON_Value)
	switch tag {
	case 1: // value.z
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(JSON_Null)
		err := b.DecodeMessage(msg)
		m.Value = &JSON_Value_Z{msg}
		return true, err
	case 2: // value.b
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(JSON_Boolean)
		err := b.DecodeMessage(msg)
		m.Value = &JSON_Value_B{msg}
		return true, err
	case 3: // value.n
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(JSON_Number)
		err := b.DecodeMessage(msg)
		m.Value = &JSON_Value_N{msg}
		return true, err
	case 4: // value.t
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(JSON_Text)
		err := b.DecodeMessage(msg)
		m.Value = &JSON_Value_T{msg}
		return true, err
	case 5: // value.a
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(JSON_Array)
		err := b.DecodeMessage(msg)
		m.Value = &JSON_Value_A{msg}
		return true, err
	case 6: // value.o
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(JSON_Object)
		err := b.DecodeMessage(msg)
		m.Value = &JSON_Value_O{msg}
		return true, err
	default:
		return false, nil
	}
}

func _JSON_Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*JSON_Value)
	// value
	switch x := m.Value.(type) {
	case *JSON_Value_Z:
		s := proto.Size(x.Z)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *JSON_Value_B:
		s := proto.Size(x.B)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *JSON_Value_N:
		s := proto.Size(x.N)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *JSON_Value_T:
		s := proto.Size(x.T)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *JSON_Value_A:
		s := proto.Size(x.A)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *JSON_Value_O:
		s := proto.Size(x.O)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*JSON)(nil), "main.JSON")
	proto.RegisterType((*JSON_Object)(nil), "main.JSON.Object")
	proto.RegisterMapType((map[string]*JSON_Value)(nil), "main.JSON.Object.ObjectEntry")
	proto.RegisterType((*JSON_Array)(nil), "main.JSON.Array")
	proto.RegisterType((*JSON_Text)(nil), "main.JSON.Text")
	proto.RegisterType((*JSON_Number)(nil), "main.JSON.Number")
	proto.RegisterType((*JSON_Boolean)(nil), "main.JSON.Boolean")
	proto.RegisterType((*JSON_Null)(nil), "main.JSON.Null")
	proto.RegisterType((*JSON_Value)(nil), "main.JSON.Value")
}

func init() { proto.RegisterFile("data_json.proto", fileDescriptor_data_json_e0526081189d52e2) }

var fileDescriptor_data_json_e0526081189d52e2 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x86, 0x71, 0x37, 0x71, 0x76, 0x27, 0x87, 0x96, 0x39, 0x40, 0x30, 0xaa, 0x1a, 0x7a, 0x40,
	0x7b, 0xca, 0x61, 0x2b, 0x24, 0x84, 0xc4, 0x81, 0x95, 0x90, 0x50, 0x91, 0xb6, 0x52, 0x40, 0x5c,
	0x23, 0x07, 0x72, 0x70, 0x71, 0x6d, 0x14, 0x3b, 0xa8, 0xed, 0x1b, 0xf1, 0x06, 0x3c, 0x0d, 0xcf,
	0x82, 0xc6, 0xf6, 0xa2, 0xa0, 0xed, 0x29, 0x63, 0xcf, 0xf7, 0xcf, 0x3f, 0x19, 0x0f, 0x1c, 0x7f,
	0x93, 0x5e, 0x76, 0xd7, 0xce, 0x9a, 0xe6, 0xc7, 0x68, 0xbd, 0xc5, 0xec, 0x46, 0x2a, 0x73, 0xfe,
	0x3b, 0x87, 0xec, 0xf2, 0xd3, 0xd5, 0x4e, 0xfc, 0x62, 0xc0, 0xaf, 0xfa, 0xeb, 0xe1, 0xab, 0xc7,
	0x57, 0xc0, 0x6d, 0x88, 0x2a, 0x56, 0x2f, 0xd6, 0xe5, 0xe6, 0xb4, 0x21, 0xb4, 0x21, 0xac, 0x89,
	0x48, 0xfa, 0xbc, 0x37, 0x7e, 0xbc, 0x6b, 0x13, 0x8c, 0xcf, 0x61, 0xa5, 0x5c, 0x97, 0x94, 0x47,
	0x35, 0x5b, 0x2f, 0xdb, 0xa5, 0x72, 0x91, 0x14, 0x1f, 0xa1, 0x9c, 0x69, 0xf0, 0x04, 0x16, 0xdf,
	0x87, 0xbb, 0x8a, 0xd5, 0x6c, 0xbd, 0x6a, 0x29, 0xc4, 0x97, 0x90, 0xff, 0x94, 0x7a, 0x1a, 0x82,
	0xb2, 0xdc, 0x9c, 0xcc, 0x3c, 0xbf, 0xd0, 0x7d, 0x1b, 0xd3, 0x6f, 0x8e, 0x5e, 0x33, 0x71, 0x09,
	0xf9, 0xbb, 0x71, 0x94, 0x41, 0x24, 0x29, 0x48, 0x8d, 0x3e, 0x20, 0x0a, 0x69, 0x7c, 0x06, 0x4b,
	0xe5, 0xba, 0x88, 0xc6, 0xce, 0x0a, 0xe5, 0x42, 0x09, 0x71, 0x01, 0xd9, 0xe7, 0xe1, 0xd6, 0x23,
	0x42, 0xe6, 0x87, 0x5b, 0x9f, 0x5a, 0x0a, 0x31, 0x3e, 0x85, 0x42, 0xb9, 0x2e, 0x5c, 0x47, 0x15,
	0x57, 0x8e, 0x60, 0xf1, 0x16, 0xf8, 0x6e, 0xba, 0xe9, 0x87, 0x11, 0x9f, 0x00, 0x37, 0x21, 0x0a,
	0x42, 0xd6, 0xa6, 0x53, 0x1a, 0x46, 0x4a, 0xfd, 0x1b, 0x46, 0x14, 0x89, 0x2d, 0x14, 0x5b, 0x6b,
	0xf5, 0x20, 0x0d, 0x56, 0x50, 0xf4, 0x31, 0x0c, 0x05, 0x96, 0xed, 0xfe, 0x88, 0xa7, 0x00, 0xca,
	0x75, 0xfb, 0x64, 0x2c, 0xb1, 0x52, 0x2e, 0x09, 0xc5, 0x19, 0x64, 0xbb, 0x49, 0xeb, 0xd4, 0xa3,
	0x99, 0xb4, 0x4e, 0x05, 0x38, 0xd9, 0x68, 0x2d, 0xfe, 0x30, 0xc8, 0xc3, 0x10, 0xf0, 0x0c, 0xd8,
	0x7d, 0x48, 0x96, 0x9b, 0xe3, 0xd9, 0x84, 0x88, 0xfa, 0xf0, 0xa8, 0x65, 0xf7, 0x78, 0x0e, 0xac,
	0x4f, 0x73, 0xc7, 0x19, 0x90, 0xac, 0x88, 0xe9, 0xf1, 0x05, 0x30, 0x53, 0x2d, 0x02, 0xf3, 0xf8,
	0xbf, 0x22, 0xf4, 0x47, 0x84, 0x18, 0xf2, 0xf1, 0x55, 0x76, 0xe0, 0x43, 0x13, 0x23, 0xc0, 0x63,
	0x0d, 0x4c, 0x56, 0xf9, 0xc1, 0xfb, 0x86, 0x87, 0x20, 0x42, 0x92, 0x8b, 0xad, 0xf8, 0x81, 0x4b,
	0x5c, 0x1d, 0x42, 0xec, 0xb6, 0x48, 0x8b, 0xd2, 0xf3, 0xb0, 0xc7, 0x17, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x9f, 0xa8, 0x68, 0xf8, 0xda, 0x02, 0x00, 0x00,
}
