// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Method int32

const (
	Method_GET     Method = 0
	Method_HEAD    Method = 1
	Method_POST    Method = 2
	Method_PUT     Method = 3
	Method_PATCH   Method = 4
	Method_DELETE  Method = 5
	Method_CONNECT Method = 6
	Method_OPTIONS Method = 7
	Method_TRACE   Method = 8
)

var Method_name = map[int32]string{
	0: "GET",
	1: "HEAD",
	2: "POST",
	3: "PUT",
	4: "PATCH",
	5: "DELETE",
	6: "CONNECT",
	7: "OPTIONS",
	8: "TRACE",
}
var Method_value = map[string]int32{
	"GET":     0,
	"HEAD":    1,
	"POST":    2,
	"PUT":     3,
	"PATCH":   4,
	"DELETE":  5,
	"CONNECT": 6,
	"OPTIONS": 7,
	"TRACE":   8,
}

func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}
func (Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{0}
}

type YmlCfg_Kind int32

const (
	YmlCfg_UNKNOWN   YmlCfg_Kind = 0
	YmlCfg_OpenAPIv3 YmlCfg_Kind = 1
)

var YmlCfg_Kind_name = map[int32]string{
	0: "UNKNOWN",
	1: "OpenAPIv3",
}
var YmlCfg_Kind_value = map[string]int32{
	"UNKNOWN":   0,
	"OpenAPIv3": 1,
}

func (x YmlCfg_Kind) String() string {
	return proto.EnumName(YmlCfg_Kind_name, int32(x))
}
func (YmlCfg_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{0, 0}
}

type Schema_JSONDraft05_TypeType int32

const (
	Schema_JSONDraft05_Type_ANY     Schema_JSONDraft05_TypeType = 0
	Schema_JSONDraft05_Type_NULL    Schema_JSONDraft05_TypeType = 1
	Schema_JSONDraft05_Type_BOOLEAN Schema_JSONDraft05_TypeType = 2
	Schema_JSONDraft05_Type_INTEGER Schema_JSONDraft05_TypeType = 3
	Schema_JSONDraft05_Type_NUMBER  Schema_JSONDraft05_TypeType = 4
	Schema_JSONDraft05_Type_ARRAY   Schema_JSONDraft05_TypeType = 5
	Schema_JSONDraft05_Type_STRING  Schema_JSONDraft05_TypeType = 6
	Schema_JSONDraft05_Type_OBJECT  Schema_JSONDraft05_TypeType = 7
)

var Schema_JSONDraft05_TypeType_name = map[int32]string{
	0: "ANY",
	1: "NULL",
	2: "BOOLEAN",
	3: "INTEGER",
	4: "NUMBER",
	5: "ARRAY",
	6: "STRING",
	7: "OBJECT",
}
var Schema_JSONDraft05_TypeType_value = map[string]int32{
	"ANY":     0,
	"NULL":    1,
	"BOOLEAN": 2,
	"INTEGER": 3,
	"NUMBER":  4,
	"ARRAY":   5,
	"STRING":  6,
	"OBJECT":  7,
}

func (x Schema_JSONDraft05_TypeType) String() string {
	return proto.EnumName(Schema_JSONDraft05_TypeType_name, int32(x))
}
func (Schema_JSONDraft05_TypeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{10, 0, 0, 0}
}

type YmlCfg struct {
	Version              uint32          `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	AuthToken            string          `protobuf:"bytes,2,opt,name=auth_token,json=authToken" json:"auth_token,omitempty"`
	Kind                 YmlCfg_Kind     `protobuf:"varint,3,opt,name=kind,enum=main.YmlCfg_Kind" json:"kind,omitempty"`
	File                 string          `protobuf:"bytes,4,opt,name=file" json:"file,omitempty"`
	Runtime              *YmlCfg_Runtime `protobuf:"bytes,5,opt,name=runtime" json:"runtime,omitempty"`
	Exec                 *YmlCfg_Exec    `protobuf:"bytes,6,opt,name=exec" json:"exec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *YmlCfg) Reset()         { *m = YmlCfg{} }
func (m *YmlCfg) String() string { return proto.CompactTextString(m) }
func (*YmlCfg) ProtoMessage()    {}
func (*YmlCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{0}
}
func (m *YmlCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YmlCfg.Unmarshal(m, b)
}
func (m *YmlCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YmlCfg.Marshal(b, m, deterministic)
}
func (dst *YmlCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YmlCfg.Merge(dst, src)
}
func (m *YmlCfg) XXX_Size() int {
	return xxx_messageInfo_YmlCfg.Size(m)
}
func (m *YmlCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_YmlCfg.DiscardUnknown(m)
}

var xxx_messageInfo_YmlCfg proto.InternalMessageInfo

func (m *YmlCfg) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *YmlCfg) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *YmlCfg) GetKind() YmlCfg_Kind {
	if m != nil {
		return m.Kind
	}
	return YmlCfg_UNKNOWN
}

func (m *YmlCfg) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *YmlCfg) GetRuntime() *YmlCfg_Runtime {
	if m != nil {
		return m.Runtime
	}
	return nil
}

func (m *YmlCfg) GetExec() *YmlCfg_Exec {
	if m != nil {
		return m.Exec
	}
	return nil
}

type YmlCfg_Runtime struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
	FinalHost            string   `protobuf:"bytes,3,opt,name=final_host,json=finalHost" json:"final_host,omitempty"`
	FinalPort            string   `protobuf:"bytes,4,opt,name=final_port,json=finalPort" json:"final_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YmlCfg_Runtime) Reset()         { *m = YmlCfg_Runtime{} }
func (m *YmlCfg_Runtime) String() string { return proto.CompactTextString(m) }
func (*YmlCfg_Runtime) ProtoMessage()    {}
func (*YmlCfg_Runtime) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{0, 0}
}
func (m *YmlCfg_Runtime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YmlCfg_Runtime.Unmarshal(m, b)
}
func (m *YmlCfg_Runtime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YmlCfg_Runtime.Marshal(b, m, deterministic)
}
func (dst *YmlCfg_Runtime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YmlCfg_Runtime.Merge(dst, src)
}
func (m *YmlCfg_Runtime) XXX_Size() int {
	return xxx_messageInfo_YmlCfg_Runtime.Size(m)
}
func (m *YmlCfg_Runtime) XXX_DiscardUnknown() {
	xxx_messageInfo_YmlCfg_Runtime.DiscardUnknown(m)
}

var xxx_messageInfo_YmlCfg_Runtime proto.InternalMessageInfo

func (m *YmlCfg_Runtime) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *YmlCfg_Runtime) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *YmlCfg_Runtime) GetFinalHost() string {
	if m != nil {
		return m.FinalHost
	}
	return ""
}

func (m *YmlCfg_Runtime) GetFinalPort() string {
	if m != nil {
		return m.FinalPort
	}
	return ""
}

type YmlCfg_Exec struct {
	Start                []string `protobuf:"bytes,1,rep,name=start" json:"start,omitempty"`
	Reset_               []string `protobuf:"bytes,2,rep,name=reset" json:"reset,omitempty"`
	Stop                 []string `protobuf:"bytes,3,rep,name=stop" json:"stop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YmlCfg_Exec) Reset()         { *m = YmlCfg_Exec{} }
func (m *YmlCfg_Exec) String() string { return proto.CompactTextString(m) }
func (*YmlCfg_Exec) ProtoMessage()    {}
func (*YmlCfg_Exec) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{0, 1}
}
func (m *YmlCfg_Exec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YmlCfg_Exec.Unmarshal(m, b)
}
func (m *YmlCfg_Exec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YmlCfg_Exec.Marshal(b, m, deterministic)
}
func (dst *YmlCfg_Exec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YmlCfg_Exec.Merge(dst, src)
}
func (m *YmlCfg_Exec) XXX_Size() int {
	return xxx_messageInfo_YmlCfg_Exec.Size(m)
}
func (m *YmlCfg_Exec) XXX_DiscardUnknown() {
	xxx_messageInfo_YmlCfg_Exec.DiscardUnknown(m)
}

var xxx_messageInfo_YmlCfg_Exec proto.InternalMessageInfo

func (m *YmlCfg_Exec) GetStart() []string {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *YmlCfg_Exec) GetReset_() []string {
	if m != nil {
		return m.Reset_
	}
	return nil
}

func (m *YmlCfg_Exec) GetStop() []string {
	if m != nil {
		return m.Stop
	}
	return nil
}

type InitFuzzing struct {
	Config               *YmlCfg  `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
	Spec                 *SpecIR  `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitFuzzing) Reset()         { *m = InitFuzzing{} }
func (m *InitFuzzing) String() string { return proto.CompactTextString(m) }
func (*InitFuzzing) ProtoMessage()    {}
func (*InitFuzzing) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{1}
}
func (m *InitFuzzing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitFuzzing.Unmarshal(m, b)
}
func (m *InitFuzzing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitFuzzing.Marshal(b, m, deterministic)
}
func (dst *InitFuzzing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitFuzzing.Merge(dst, src)
}
func (m *InitFuzzing) XXX_Size() int {
	return xxx_messageInfo_InitFuzzing.Size(m)
}
func (m *InitFuzzing) XXX_DiscardUnknown() {
	xxx_messageInfo_InitFuzzing.DiscardUnknown(m)
}

var xxx_messageInfo_InitFuzzing proto.InternalMessageInfo

func (m *InitFuzzing) GetConfig() *YmlCfg {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *InitFuzzing) GetSpec() *SpecIR {
	if m != nil {
		return m.Spec
	}
	return nil
}

type SpecIR struct {
	// map<Ptr,string> ptrs = 1; //FIXME: really needed?
	// Since order is preserved, offset in this list can be used as uint32
	Ptrs                 []string    `protobuf:"bytes,1,rep,name=ptrs" json:"ptrs,omitempty"`
	Schemas              *Schemas    `protobuf:"bytes,2,opt,name=schemas" json:"schemas,omitempty"`
	Endpoints            []*Endpoint `protobuf:"bytes,3,rep,name=endpoints" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SpecIR) Reset()         { *m = SpecIR{} }
func (m *SpecIR) String() string { return proto.CompactTextString(m) }
func (*SpecIR) ProtoMessage()    {}
func (*SpecIR) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{2}
}
func (m *SpecIR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecIR.Unmarshal(m, b)
}
func (m *SpecIR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecIR.Marshal(b, m, deterministic)
}
func (dst *SpecIR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecIR.Merge(dst, src)
}
func (m *SpecIR) XXX_Size() int {
	return xxx_messageInfo_SpecIR.Size(m)
}
func (m *SpecIR) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecIR.DiscardUnknown(m)
}

var xxx_messageInfo_SpecIR proto.InternalMessageInfo

func (m *SpecIR) GetPtrs() []string {
	if m != nil {
		return m.Ptrs
	}
	return nil
}

func (m *SpecIR) GetSchemas() *Schemas {
	if m != nil {
		return m.Schemas
	}
	return nil
}

func (m *SpecIR) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type Schemas struct {
	Schemas_JSONDraft05  map[string]*Schema_JSONDraft05 `protobuf:"bytes,1,rep,name=schemas_JSONDraft05,json=schemasJSONDraft05" json:"schemas_JSONDraft05,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Schemas) Reset()         { *m = Schemas{} }
func (m *Schemas) String() string { return proto.CompactTextString(m) }
func (*Schemas) ProtoMessage()    {}
func (*Schemas) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{3}
}
func (m *Schemas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schemas.Unmarshal(m, b)
}
func (m *Schemas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schemas.Marshal(b, m, deterministic)
}
func (dst *Schemas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schemas.Merge(dst, src)
}
func (m *Schemas) XXX_Size() int {
	return xxx_messageInfo_Schemas.Size(m)
}
func (m *Schemas) XXX_DiscardUnknown() {
	xxx_messageInfo_Schemas.DiscardUnknown(m)
}

var xxx_messageInfo_Schemas proto.InternalMessageInfo

func (m *Schemas) GetSchemas_JSONDraft05() map[string]*Schema_JSONDraft05 {
	if m != nil {
		return m.Schemas_JSONDraft05
	}
	return nil
}

type Endpoint struct {
	// Types that are valid to be assigned to Endpoint:
	//	*Endpoint_Endpoint_JSONDraft05
	Endpoint             isEndpoint_Endpoint `protobuf_oneof:"endpoint"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{4}
}
func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (dst *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(dst, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

type isEndpoint_Endpoint interface {
	isEndpoint_Endpoint()
}

type Endpoint_Endpoint_JSONDraft05 struct {
	Endpoint_JSONDraft05 *EndpointJSONDraft05 `protobuf:"bytes,1,opt,name=endpoint_JSONDraft05,json=endpointJSONDraft05,oneof"`
}

func (*Endpoint_Endpoint_JSONDraft05) isEndpoint_Endpoint() {}

func (m *Endpoint) GetEndpoint() isEndpoint_Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

func (m *Endpoint) GetEndpoint_JSONDraft05() *EndpointJSONDraft05 {
	if x, ok := m.GetEndpoint().(*Endpoint_Endpoint_JSONDraft05); ok {
		return x.Endpoint_JSONDraft05
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Endpoint) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Endpoint_OneofMarshaler, _Endpoint_OneofUnmarshaler, _Endpoint_OneofSizer, []interface{}{
		(*Endpoint_Endpoint_JSONDraft05)(nil),
	}
}

func _Endpoint_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Endpoint)
	// endpoint
	switch x := m.Endpoint.(type) {
	case *Endpoint_Endpoint_JSONDraft05:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Endpoint_JSONDraft05); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Endpoint.Endpoint has unexpected type %T", x)
	}
	return nil
}

func _Endpoint_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Endpoint)
	switch tag {
	case 1: // endpoint.endpoint_JSONDraft05
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EndpointJSONDraft05)
		err := b.DecodeMessage(msg)
		m.Endpoint = &Endpoint_Endpoint_JSONDraft05{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Endpoint_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Endpoint)
	// endpoint
	switch x := m.Endpoint.(type) {
	case *Endpoint_Endpoint_JSONDraft05:
		s := proto.Size(x.Endpoint_JSONDraft05)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type EndpointJSONDraft05 struct {
	Method Method             `protobuf:"varint,1,opt,name=method,enum=main.Method" json:"method,omitempty"`
	Path   *Path              `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Params *ParamsJSONDraft05 `protobuf:"bytes,3,opt,name=params" json:"params,omitempty"`
	// This uint32 replaces an enum of 1XX,...,201,204,...,5XX,XXX.
	Outputs              map[uint32]*PtrOrSchemaJSONDraft05 `protobuf:"bytes,4,rep,name=outputs" json:"outputs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *EndpointJSONDraft05) Reset()         { *m = EndpointJSONDraft05{} }
func (m *EndpointJSONDraft05) String() string { return proto.CompactTextString(m) }
func (*EndpointJSONDraft05) ProtoMessage()    {}
func (*EndpointJSONDraft05) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{5}
}
func (m *EndpointJSONDraft05) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointJSONDraft05.Unmarshal(m, b)
}
func (m *EndpointJSONDraft05) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointJSONDraft05.Marshal(b, m, deterministic)
}
func (dst *EndpointJSONDraft05) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointJSONDraft05.Merge(dst, src)
}
func (m *EndpointJSONDraft05) XXX_Size() int {
	return xxx_messageInfo_EndpointJSONDraft05.Size(m)
}
func (m *EndpointJSONDraft05) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointJSONDraft05.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointJSONDraft05 proto.InternalMessageInfo

func (m *EndpointJSONDraft05) GetMethod() Method {
	if m != nil {
		return m.Method
	}
	return Method_GET
}

func (m *EndpointJSONDraft05) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *EndpointJSONDraft05) GetParams() *ParamsJSONDraft05 {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *EndpointJSONDraft05) GetOutputs() map[uint32]*PtrOrSchemaJSONDraft05 {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type Path struct {
	Partial              []*Path_PathPartial `protobuf:"bytes,1,rep,name=partial" json:"partial,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{6}
}
func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (dst *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(dst, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetPartial() []*Path_PathPartial {
	if m != nil {
		return m.Partial
	}
	return nil
}

type Path_PathPartial struct {
	// Types that are valid to be assigned to Pp:
	//	*Path_PathPartial_Part
	//	*Path_PathPartial_Ptr
	Pp                   isPath_PathPartial_Pp `protobuf_oneof:"pp"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Path_PathPartial) Reset()         { *m = Path_PathPartial{} }
func (m *Path_PathPartial) String() string { return proto.CompactTextString(m) }
func (*Path_PathPartial) ProtoMessage()    {}
func (*Path_PathPartial) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{6, 0}
}
func (m *Path_PathPartial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path_PathPartial.Unmarshal(m, b)
}
func (m *Path_PathPartial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path_PathPartial.Marshal(b, m, deterministic)
}
func (dst *Path_PathPartial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path_PathPartial.Merge(dst, src)
}
func (m *Path_PathPartial) XXX_Size() int {
	return xxx_messageInfo_Path_PathPartial.Size(m)
}
func (m *Path_PathPartial) XXX_DiscardUnknown() {
	xxx_messageInfo_Path_PathPartial.DiscardUnknown(m)
}

var xxx_messageInfo_Path_PathPartial proto.InternalMessageInfo

type isPath_PathPartial_Pp interface {
	isPath_PathPartial_Pp()
}

type Path_PathPartial_Part struct {
	Part string `protobuf:"bytes,1,opt,name=part,oneof"`
}
type Path_PathPartial_Ptr struct {
	Ptr uint32 `protobuf:"varint,2,opt,name=ptr,oneof"`
}

func (*Path_PathPartial_Part) isPath_PathPartial_Pp() {}
func (*Path_PathPartial_Ptr) isPath_PathPartial_Pp()  {}

func (m *Path_PathPartial) GetPp() isPath_PathPartial_Pp {
	if m != nil {
		return m.Pp
	}
	return nil
}

func (m *Path_PathPartial) GetPart() string {
	if x, ok := m.GetPp().(*Path_PathPartial_Part); ok {
		return x.Part
	}
	return ""
}

func (m *Path_PathPartial) GetPtr() uint32 {
	if x, ok := m.GetPp().(*Path_PathPartial_Ptr); ok {
		return x.Ptr
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Path_PathPartial) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Path_PathPartial_OneofMarshaler, _Path_PathPartial_OneofUnmarshaler, _Path_PathPartial_OneofSizer, []interface{}{
		(*Path_PathPartial_Part)(nil),
		(*Path_PathPartial_Ptr)(nil),
	}
}

func _Path_PathPartial_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Path_PathPartial)
	// pp
	switch x := m.Pp.(type) {
	case *Path_PathPartial_Part:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Part)
	case *Path_PathPartial_Ptr:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Ptr))
	case nil:
	default:
		return fmt.Errorf("Path_PathPartial.Pp has unexpected type %T", x)
	}
	return nil
}

func _Path_PathPartial_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Path_PathPartial)
	switch tag {
	case 1: // pp.part
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Pp = &Path_PathPartial_Part{x}
		return true, err
	case 2: // pp.ptr
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Pp = &Path_PathPartial_Ptr{uint32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _Path_PathPartial_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Path_PathPartial)
	// pp
	switch x := m.Pp.(type) {
	case *Path_PathPartial_Part:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Part)))
		n += len(x.Part)
	case *Path_PathPartial_Ptr:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Ptr))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ParamsJSONDraft05 struct {
	// These uint32s are Ptrs
	Header               map[uint32]*ParamJSONDraft05 `protobuf:"bytes,1,rep,name=header" json:"header,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Path                 map[uint32]*ParamJSONDraft05 `protobuf:"bytes,2,rep,name=path" json:"path,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body                 map[uint32]*ParamJSONDraft05 `protobuf:"bytes,3,rep,name=body" json:"body,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Query                map[uint32]*ParamJSONDraft05 `protobuf:"bytes,4,rep,name=query" json:"query,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ParamsJSONDraft05) Reset()         { *m = ParamsJSONDraft05{} }
func (m *ParamsJSONDraft05) String() string { return proto.CompactTextString(m) }
func (*ParamsJSONDraft05) ProtoMessage()    {}
func (*ParamsJSONDraft05) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{7}
}
func (m *ParamsJSONDraft05) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParamsJSONDraft05.Unmarshal(m, b)
}
func (m *ParamsJSONDraft05) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParamsJSONDraft05.Marshal(b, m, deterministic)
}
func (dst *ParamsJSONDraft05) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamsJSONDraft05.Merge(dst, src)
}
func (m *ParamsJSONDraft05) XXX_Size() int {
	return xxx_messageInfo_ParamsJSONDraft05.Size(m)
}
func (m *ParamsJSONDraft05) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamsJSONDraft05.DiscardUnknown(m)
}

var xxx_messageInfo_ParamsJSONDraft05 proto.InternalMessageInfo

func (m *ParamsJSONDraft05) GetHeader() map[uint32]*ParamJSONDraft05 {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ParamsJSONDraft05) GetPath() map[uint32]*ParamJSONDraft05 {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *ParamsJSONDraft05) GetBody() map[uint32]*ParamJSONDraft05 {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *ParamsJSONDraft05) GetQuery() map[uint32]*ParamJSONDraft05 {
	if m != nil {
		return m.Query
	}
	return nil
}

type ParamJSONDraft05 struct {
	SchemaOrPtr          *PtrOrSchemaJSONDraft05 `protobuf:"bytes,1,opt,name=schema_or_ptr,json=schemaOrPtr" json:"schema_or_ptr,omitempty"`
	Required             bool                    `protobuf:"varint,2,opt,name=required" json:"required,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ParamJSONDraft05) Reset()         { *m = ParamJSONDraft05{} }
func (m *ParamJSONDraft05) String() string { return proto.CompactTextString(m) }
func (*ParamJSONDraft05) ProtoMessage()    {}
func (*ParamJSONDraft05) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{8}
}
func (m *ParamJSONDraft05) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParamJSONDraft05.Unmarshal(m, b)
}
func (m *ParamJSONDraft05) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParamJSONDraft05.Marshal(b, m, deterministic)
}
func (dst *ParamJSONDraft05) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamJSONDraft05.Merge(dst, src)
}
func (m *ParamJSONDraft05) XXX_Size() int {
	return xxx_messageInfo_ParamJSONDraft05.Size(m)
}
func (m *ParamJSONDraft05) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamJSONDraft05.DiscardUnknown(m)
}

var xxx_messageInfo_ParamJSONDraft05 proto.InternalMessageInfo

func (m *ParamJSONDraft05) GetSchemaOrPtr() *PtrOrSchemaJSONDraft05 {
	if m != nil {
		return m.SchemaOrPtr
	}
	return nil
}

func (m *ParamJSONDraft05) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

type PtrOrSchemaJSONDraft05 struct {
	// Types that are valid to be assigned to PtrOrSchema_JSONDraft05:
	//	*PtrOrSchemaJSONDraft05_Ptr
	//	*PtrOrSchemaJSONDraft05_Schema
	PtrOrSchema_JSONDraft05 isPtrOrSchemaJSONDraft05_PtrOrSchema_JSONDraft05 `protobuf_oneof:"ptr_or_schema_JSONDraft05"`
	XXX_NoUnkeyedLiteral    struct{}                                         `json:"-"`
	XXX_unrecognized        []byte                                           `json:"-"`
	XXX_sizecache           int32                                            `json:"-"`
}

func (m *PtrOrSchemaJSONDraft05) Reset()         { *m = PtrOrSchemaJSONDraft05{} }
func (m *PtrOrSchemaJSONDraft05) String() string { return proto.CompactTextString(m) }
func (*PtrOrSchemaJSONDraft05) ProtoMessage()    {}
func (*PtrOrSchemaJSONDraft05) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{9}
}
func (m *PtrOrSchemaJSONDraft05) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PtrOrSchemaJSONDraft05.Unmarshal(m, b)
}
func (m *PtrOrSchemaJSONDraft05) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PtrOrSchemaJSONDraft05.Marshal(b, m, deterministic)
}
func (dst *PtrOrSchemaJSONDraft05) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PtrOrSchemaJSONDraft05.Merge(dst, src)
}
func (m *PtrOrSchemaJSONDraft05) XXX_Size() int {
	return xxx_messageInfo_PtrOrSchemaJSONDraft05.Size(m)
}
func (m *PtrOrSchemaJSONDraft05) XXX_DiscardUnknown() {
	xxx_messageInfo_PtrOrSchemaJSONDraft05.DiscardUnknown(m)
}

var xxx_messageInfo_PtrOrSchemaJSONDraft05 proto.InternalMessageInfo

type isPtrOrSchemaJSONDraft05_PtrOrSchema_JSONDraft05 interface {
	isPtrOrSchemaJSONDraft05_PtrOrSchema_JSONDraft05()
}

type PtrOrSchemaJSONDraft05_Ptr struct {
	Ptr uint32 `protobuf:"varint,1,opt,name=ptr,oneof"`
}
type PtrOrSchemaJSONDraft05_Schema struct {
	Schema *Schema_JSONDraft05 `protobuf:"bytes,2,opt,name=schema,oneof"`
}

func (*PtrOrSchemaJSONDraft05_Ptr) isPtrOrSchemaJSONDraft05_PtrOrSchema_JSONDraft05()    {}
func (*PtrOrSchemaJSONDraft05_Schema) isPtrOrSchemaJSONDraft05_PtrOrSchema_JSONDraft05() {}

func (m *PtrOrSchemaJSONDraft05) GetPtrOrSchema_JSONDraft05() isPtrOrSchemaJSONDraft05_PtrOrSchema_JSONDraft05 {
	if m != nil {
		return m.PtrOrSchema_JSONDraft05
	}
	return nil
}

func (m *PtrOrSchemaJSONDraft05) GetPtr() uint32 {
	if x, ok := m.GetPtrOrSchema_JSONDraft05().(*PtrOrSchemaJSONDraft05_Ptr); ok {
		return x.Ptr
	}
	return 0
}

func (m *PtrOrSchemaJSONDraft05) GetSchema() *Schema_JSONDraft05 {
	if x, ok := m.GetPtrOrSchema_JSONDraft05().(*PtrOrSchemaJSONDraft05_Schema); ok {
		return x.Schema
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PtrOrSchemaJSONDraft05) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PtrOrSchemaJSONDraft05_OneofMarshaler, _PtrOrSchemaJSONDraft05_OneofUnmarshaler, _PtrOrSchemaJSONDraft05_OneofSizer, []interface{}{
		(*PtrOrSchemaJSONDraft05_Ptr)(nil),
		(*PtrOrSchemaJSONDraft05_Schema)(nil),
	}
}

func _PtrOrSchemaJSONDraft05_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PtrOrSchemaJSONDraft05)
	// ptr_or_schema_JSONDraft05
	switch x := m.PtrOrSchema_JSONDraft05.(type) {
	case *PtrOrSchemaJSONDraft05_Ptr:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Ptr))
	case *PtrOrSchemaJSONDraft05_Schema:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Schema); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PtrOrSchemaJSONDraft05.PtrOrSchema_JSONDraft05 has unexpected type %T", x)
	}
	return nil
}

func _PtrOrSchemaJSONDraft05_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PtrOrSchemaJSONDraft05)
	switch tag {
	case 1: // ptr_or_schema_JSONDraft05.ptr
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.PtrOrSchema_JSONDraft05 = &PtrOrSchemaJSONDraft05_Ptr{uint32(x)}
		return true, err
	case 2: // ptr_or_schema_JSONDraft05.schema
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Schema_JSONDraft05)
		err := b.DecodeMessage(msg)
		m.PtrOrSchema_JSONDraft05 = &PtrOrSchemaJSONDraft05_Schema{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PtrOrSchemaJSONDraft05_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PtrOrSchemaJSONDraft05)
	// ptr_or_schema_JSONDraft05
	switch x := m.PtrOrSchema_JSONDraft05.(type) {
	case *PtrOrSchemaJSONDraft05_Ptr:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Ptr))
	case *PtrOrSchemaJSONDraft05_Schema:
		s := proto.Size(x.Schema)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Schema struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schema) Reset()         { *m = Schema{} }
func (m *Schema) String() string { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()    {}
func (*Schema) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{10}
}
func (m *Schema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema.Unmarshal(m, b)
}
func (m *Schema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema.Marshal(b, m, deterministic)
}
func (dst *Schema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema.Merge(dst, src)
}
func (m *Schema) XXX_Size() int {
	return xxx_messageInfo_Schema.Size(m)
}
func (m *Schema) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema.DiscardUnknown(m)
}

var xxx_messageInfo_Schema proto.InternalMessageInfo

type Schema_JSONDraft05 struct {
	Type []*Schema_JSONDraft05_Type `protobuf:"bytes,1,rep,name=type" json:"type,omitempty"`
	Enum *JSON_Array                `protobuf:"bytes,2,opt,name=enum" json:"enum,omitempty"`
	// type: string
	Format       string `protobuf:"bytes,3,opt,name=format" json:"format,omitempty"`
	MinLength    uint64 `protobuf:"varint,4,opt,name=min_length,json=minLength" json:"min_length,omitempty"`
	MaxLength    uint64 `protobuf:"varint,5,opt,name=max_length,json=maxLength" json:"max_length,omitempty"`
	HasMaxLength bool   `protobuf:"varint,6,opt,name=has_max_length,json=hasMaxLength" json:"has_max_length,omitempty"`
	Pattern      string `protobuf:"bytes,7,opt,name=pattern" json:"pattern,omitempty"`
	// type: number | integer
	Minimum              float64 `protobuf:"fixed64,8,opt,name=minimum" json:"minimum,omitempty"`
	Maximum              float64 `protobuf:"fixed64,9,opt,name=maximum" json:"maximum,omitempty"`
	HasMinimum           bool    `protobuf:"varint,10,opt,name=has_minimum,json=hasMinimum" json:"has_minimum,omitempty"`
	HasMaximum           bool    `protobuf:"varint,11,opt,name=has_maximum,json=hasMaximum" json:"has_maximum,omitempty"`
	TranslatedMultipleOf float64 `protobuf:"fixed64,12,opt,name=translated_multiple_of,json=translatedMultipleOf" json:"translated_multiple_of,omitempty"`
	ExclusiveMinimum     bool    `protobuf:"varint,13,opt,name=exclusive_minimum,json=exclusiveMinimum" json:"exclusive_minimum,omitempty"`
	ExclusiveMaximum     bool    `protobuf:"varint,14,opt,name=exclusive_maximum,json=exclusiveMaximum" json:"exclusive_maximum,omitempty"`
	// type: array
	Items       []*PtrOrSchemaJSONDraft05 `protobuf:"bytes,15,rep,name=items" json:"items,omitempty"`
	UniqueItems bool                      `protobuf:"varint,16,opt,name=unique_items,json=uniqueItems" json:"unique_items,omitempty"`
	MinItems    uint64                    `protobuf:"varint,17,opt,name=min_items,json=minItems" json:"min_items,omitempty"`
	MaxItems    uint64                    `protobuf:"varint,18,opt,name=max_items,json=maxItems" json:"max_items,omitempty"`
	HasMaxItems bool                      `protobuf:"varint,19,opt,name=has_max_items,json=hasMaxItems" json:"has_max_items,omitempty"`
	// type: object
	Properties              map[string]*PtrOrSchemaJSONDraft05       `protobuf:"bytes,20,rep,name=properties" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Required                []string                                 `protobuf:"bytes,21,rep,name=required" json:"required,omitempty"`
	MinProperties           uint64                                   `protobuf:"varint,22,opt,name=min_properties,json=minProperties" json:"min_properties,omitempty"`
	MaxProperties           uint64                                   `protobuf:"varint,23,opt,name=max_properties,json=maxProperties" json:"max_properties,omitempty"`
	HasMaxProperties        bool                                     `protobuf:"varint,24,opt,name=has_max_properties,json=hasMaxProperties" json:"has_max_properties,omitempty"`
	AdditionalProperties    *Schema_JSONDraft05_AdditionalProperties `protobuf:"bytes,25,opt,name=additional_properties,json=additionalProperties" json:"additional_properties,omitempty"`
	HasAdditionalProperties bool                                     `protobuf:"varint,26,opt,name=has_additional_properties,json=hasAdditionalProperties" json:"has_additional_properties,omitempty"`
	AllOf                   []*PtrOrSchemaJSONDraft05                `protobuf:"bytes,27,rep,name=all_of,json=allOf" json:"all_of,omitempty"`
	AnyOf                   []*PtrOrSchemaJSONDraft05                `protobuf:"bytes,28,rep,name=any_of,json=anyOf" json:"any_of,omitempty"`
	OneOf                   []*PtrOrSchemaJSONDraft05                `protobuf:"bytes,29,rep,name=one_of,json=oneOf" json:"one_of,omitempty"`
	Not                     *Schema_JSONDraft05                      `protobuf:"bytes,30,opt,name=not" json:"not,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                                 `json:"-"`
	XXX_unrecognized        []byte                                   `json:"-"`
	XXX_sizecache           int32                                    `json:"-"`
}

func (m *Schema_JSONDraft05) Reset()         { *m = Schema_JSONDraft05{} }
func (m *Schema_JSONDraft05) String() string { return proto.CompactTextString(m) }
func (*Schema_JSONDraft05) ProtoMessage()    {}
func (*Schema_JSONDraft05) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{10, 0}
}
func (m *Schema_JSONDraft05) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema_JSONDraft05.Unmarshal(m, b)
}
func (m *Schema_JSONDraft05) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema_JSONDraft05.Marshal(b, m, deterministic)
}
func (dst *Schema_JSONDraft05) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema_JSONDraft05.Merge(dst, src)
}
func (m *Schema_JSONDraft05) XXX_Size() int {
	return xxx_messageInfo_Schema_JSONDraft05.Size(m)
}
func (m *Schema_JSONDraft05) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema_JSONDraft05.DiscardUnknown(m)
}

var xxx_messageInfo_Schema_JSONDraft05 proto.InternalMessageInfo

func (m *Schema_JSONDraft05) GetType() []*Schema_JSONDraft05_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Schema_JSONDraft05) GetEnum() *JSON_Array {
	if m != nil {
		return m.Enum
	}
	return nil
}

func (m *Schema_JSONDraft05) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Schema_JSONDraft05) GetMinLength() uint64 {
	if m != nil {
		return m.MinLength
	}
	return 0
}

func (m *Schema_JSONDraft05) GetMaxLength() uint64 {
	if m != nil {
		return m.MaxLength
	}
	return 0
}

func (m *Schema_JSONDraft05) GetHasMaxLength() bool {
	if m != nil {
		return m.HasMaxLength
	}
	return false
}

func (m *Schema_JSONDraft05) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *Schema_JSONDraft05) GetMinimum() float64 {
	if m != nil {
		return m.Minimum
	}
	return 0
}

func (m *Schema_JSONDraft05) GetMaximum() float64 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

func (m *Schema_JSONDraft05) GetHasMinimum() bool {
	if m != nil {
		return m.HasMinimum
	}
	return false
}

func (m *Schema_JSONDraft05) GetHasMaximum() bool {
	if m != nil {
		return m.HasMaximum
	}
	return false
}

func (m *Schema_JSONDraft05) GetTranslatedMultipleOf() float64 {
	if m != nil {
		return m.TranslatedMultipleOf
	}
	return 0
}

func (m *Schema_JSONDraft05) GetExclusiveMinimum() bool {
	if m != nil {
		return m.ExclusiveMinimum
	}
	return false
}

func (m *Schema_JSONDraft05) GetExclusiveMaximum() bool {
	if m != nil {
		return m.ExclusiveMaximum
	}
	return false
}

func (m *Schema_JSONDraft05) GetItems() []*PtrOrSchemaJSONDraft05 {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Schema_JSONDraft05) GetUniqueItems() bool {
	if m != nil {
		return m.UniqueItems
	}
	return false
}

func (m *Schema_JSONDraft05) GetMinItems() uint64 {
	if m != nil {
		return m.MinItems
	}
	return 0
}

func (m *Schema_JSONDraft05) GetMaxItems() uint64 {
	if m != nil {
		return m.MaxItems
	}
	return 0
}

func (m *Schema_JSONDraft05) GetHasMaxItems() bool {
	if m != nil {
		return m.HasMaxItems
	}
	return false
}

func (m *Schema_JSONDraft05) GetProperties() map[string]*PtrOrSchemaJSONDraft05 {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Schema_JSONDraft05) GetRequired() []string {
	if m != nil {
		return m.Required
	}
	return nil
}

func (m *Schema_JSONDraft05) GetMinProperties() uint64 {
	if m != nil {
		return m.MinProperties
	}
	return 0
}

func (m *Schema_JSONDraft05) GetMaxProperties() uint64 {
	if m != nil {
		return m.MaxProperties
	}
	return 0
}

func (m *Schema_JSONDraft05) GetHasMaxProperties() bool {
	if m != nil {
		return m.HasMaxProperties
	}
	return false
}

func (m *Schema_JSONDraft05) GetAdditionalProperties() *Schema_JSONDraft05_AdditionalProperties {
	if m != nil {
		return m.AdditionalProperties
	}
	return nil
}

func (m *Schema_JSONDraft05) GetHasAdditionalProperties() bool {
	if m != nil {
		return m.HasAdditionalProperties
	}
	return false
}

func (m *Schema_JSONDraft05) GetAllOf() []*PtrOrSchemaJSONDraft05 {
	if m != nil {
		return m.AllOf
	}
	return nil
}

func (m *Schema_JSONDraft05) GetAnyOf() []*PtrOrSchemaJSONDraft05 {
	if m != nil {
		return m.AnyOf
	}
	return nil
}

func (m *Schema_JSONDraft05) GetOneOf() []*PtrOrSchemaJSONDraft05 {
	if m != nil {
		return m.OneOf
	}
	return nil
}

func (m *Schema_JSONDraft05) GetNot() *Schema_JSONDraft05 {
	if m != nil {
		return m.Not
	}
	return nil
}

type Schema_JSONDraft05_Type struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schema_JSONDraft05_Type) Reset()         { *m = Schema_JSONDraft05_Type{} }
func (m *Schema_JSONDraft05_Type) String() string { return proto.CompactTextString(m) }
func (*Schema_JSONDraft05_Type) ProtoMessage()    {}
func (*Schema_JSONDraft05_Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{10, 0, 0}
}
func (m *Schema_JSONDraft05_Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema_JSONDraft05_Type.Unmarshal(m, b)
}
func (m *Schema_JSONDraft05_Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema_JSONDraft05_Type.Marshal(b, m, deterministic)
}
func (dst *Schema_JSONDraft05_Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema_JSONDraft05_Type.Merge(dst, src)
}
func (m *Schema_JSONDraft05_Type) XXX_Size() int {
	return xxx_messageInfo_Schema_JSONDraft05_Type.Size(m)
}
func (m *Schema_JSONDraft05_Type) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema_JSONDraft05_Type.DiscardUnknown(m)
}

var xxx_messageInfo_Schema_JSONDraft05_Type proto.InternalMessageInfo

type Schema_JSONDraft05_AdditionalProperties struct {
	// Types that are valid to be assigned to AddProps:
	//	*Schema_JSONDraft05_AdditionalProperties_Has
	//	*Schema_JSONDraft05_AdditionalProperties_SchemaOrPtr
	AddProps             isSchema_JSONDraft05_AdditionalProperties_AddProps `protobuf_oneof:"add_props"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *Schema_JSONDraft05_AdditionalProperties) Reset() {
	*m = Schema_JSONDraft05_AdditionalProperties{}
}
func (m *Schema_JSONDraft05_AdditionalProperties) String() string { return proto.CompactTextString(m) }
func (*Schema_JSONDraft05_AdditionalProperties) ProtoMessage()    {}
func (*Schema_JSONDraft05_AdditionalProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{10, 0, 2}
}
func (m *Schema_JSONDraft05_AdditionalProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema_JSONDraft05_AdditionalProperties.Unmarshal(m, b)
}
func (m *Schema_JSONDraft05_AdditionalProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema_JSONDraft05_AdditionalProperties.Marshal(b, m, deterministic)
}
func (dst *Schema_JSONDraft05_AdditionalProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema_JSONDraft05_AdditionalProperties.Merge(dst, src)
}
func (m *Schema_JSONDraft05_AdditionalProperties) XXX_Size() int {
	return xxx_messageInfo_Schema_JSONDraft05_AdditionalProperties.Size(m)
}
func (m *Schema_JSONDraft05_AdditionalProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema_JSONDraft05_AdditionalProperties.DiscardUnknown(m)
}

var xxx_messageInfo_Schema_JSONDraft05_AdditionalProperties proto.InternalMessageInfo

type isSchema_JSONDraft05_AdditionalProperties_AddProps interface {
	isSchema_JSONDraft05_AdditionalProperties_AddProps()
}

type Schema_JSONDraft05_AdditionalProperties_Has struct {
	Has bool `protobuf:"varint,1,opt,name=has,oneof"`
}
type Schema_JSONDraft05_AdditionalProperties_SchemaOrPtr struct {
	SchemaOrPtr *PtrOrSchemaJSONDraft05 `protobuf:"bytes,2,opt,name=schema_or_ptr,json=schemaOrPtr,oneof"`
}

func (*Schema_JSONDraft05_AdditionalProperties_Has) isSchema_JSONDraft05_AdditionalProperties_AddProps() {
}
func (*Schema_JSONDraft05_AdditionalProperties_SchemaOrPtr) isSchema_JSONDraft05_AdditionalProperties_AddProps() {
}

func (m *Schema_JSONDraft05_AdditionalProperties) GetAddProps() isSchema_JSONDraft05_AdditionalProperties_AddProps {
	if m != nil {
		return m.AddProps
	}
	return nil
}

func (m *Schema_JSONDraft05_AdditionalProperties) GetHas() bool {
	if x, ok := m.GetAddProps().(*Schema_JSONDraft05_AdditionalProperties_Has); ok {
		return x.Has
	}
	return false
}

func (m *Schema_JSONDraft05_AdditionalProperties) GetSchemaOrPtr() *PtrOrSchemaJSONDraft05 {
	if x, ok := m.GetAddProps().(*Schema_JSONDraft05_AdditionalProperties_SchemaOrPtr); ok {
		return x.SchemaOrPtr
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Schema_JSONDraft05_AdditionalProperties) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Schema_JSONDraft05_AdditionalProperties_OneofMarshaler, _Schema_JSONDraft05_AdditionalProperties_OneofUnmarshaler, _Schema_JSONDraft05_AdditionalProperties_OneofSizer, []interface{}{
		(*Schema_JSONDraft05_AdditionalProperties_Has)(nil),
		(*Schema_JSONDraft05_AdditionalProperties_SchemaOrPtr)(nil),
	}
}

func _Schema_JSONDraft05_AdditionalProperties_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Schema_JSONDraft05_AdditionalProperties)
	// add_props
	switch x := m.AddProps.(type) {
	case *Schema_JSONDraft05_AdditionalProperties_Has:
		t := uint64(0)
		if x.Has {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Schema_JSONDraft05_AdditionalProperties_SchemaOrPtr:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SchemaOrPtr); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Schema_JSONDraft05_AdditionalProperties.AddProps has unexpected type %T", x)
	}
	return nil
}

func _Schema_JSONDraft05_AdditionalProperties_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Schema_JSONDraft05_AdditionalProperties)
	switch tag {
	case 1: // add_props.has
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.AddProps = &Schema_JSONDraft05_AdditionalProperties_Has{x != 0}
		return true, err
	case 2: // add_props.schema_or_ptr
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PtrOrSchemaJSONDraft05)
		err := b.DecodeMessage(msg)
		m.AddProps = &Schema_JSONDraft05_AdditionalProperties_SchemaOrPtr{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Schema_JSONDraft05_AdditionalProperties_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Schema_JSONDraft05_AdditionalProperties)
	// add_props
	switch x := m.AddProps.(type) {
	case *Schema_JSONDraft05_AdditionalProperties_Has:
		n += 1 // tag and wire
		n += 1
	case *Schema_JSONDraft05_AdditionalProperties_SchemaOrPtr:
		s := proto.Size(x.SchemaOrPtr)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type JSON struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JSON) Reset()         { *m = JSON{} }
func (m *JSON) String() string { return proto.CompactTextString(m) }
func (*JSON) ProtoMessage()    {}
func (*JSON) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{11}
}
func (m *JSON) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSON.Unmarshal(m, b)
}
func (m *JSON) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSON.Marshal(b, m, deterministic)
}
func (dst *JSON) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSON.Merge(dst, src)
}
func (m *JSON) XXX_Size() int {
	return xxx_messageInfo_JSON.Size(m)
}
func (m *JSON) XXX_DiscardUnknown() {
	xxx_messageInfo_JSON.DiscardUnknown(m)
}

var xxx_messageInfo_JSON proto.InternalMessageInfo

type JSON_Object struct {
	Object               map[string]*JSON_Value `protobuf:"bytes,1,rep,name=object" json:"object,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *JSON_Object) Reset()         { *m = JSON_Object{} }
func (m *JSON_Object) String() string { return proto.CompactTextString(m) }
func (*JSON_Object) ProtoMessage()    {}
func (*JSON_Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{11, 0}
}
func (m *JSON_Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSON_Object.Unmarshal(m, b)
}
func (m *JSON_Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSON_Object.Marshal(b, m, deterministic)
}
func (dst *JSON_Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSON_Object.Merge(dst, src)
}
func (m *JSON_Object) XXX_Size() int {
	return xxx_messageInfo_JSON_Object.Size(m)
}
func (m *JSON_Object) XXX_DiscardUnknown() {
	xxx_messageInfo_JSON_Object.DiscardUnknown(m)
}

var xxx_messageInfo_JSON_Object proto.InternalMessageInfo

func (m *JSON_Object) GetObject() map[string]*JSON_Value {
	if m != nil {
		return m.Object
	}
	return nil
}

type JSON_Array struct {
	Array                []*JSON_Value `protobuf:"bytes,1,rep,name=array" json:"array,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *JSON_Array) Reset()         { *m = JSON_Array{} }
func (m *JSON_Array) String() string { return proto.CompactTextString(m) }
func (*JSON_Array) ProtoMessage()    {}
func (*JSON_Array) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{11, 1}
}
func (m *JSON_Array) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSON_Array.Unmarshal(m, b)
}
func (m *JSON_Array) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSON_Array.Marshal(b, m, deterministic)
}
func (dst *JSON_Array) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSON_Array.Merge(dst, src)
}
func (m *JSON_Array) XXX_Size() int {
	return xxx_messageInfo_JSON_Array.Size(m)
}
func (m *JSON_Array) XXX_DiscardUnknown() {
	xxx_messageInfo_JSON_Array.DiscardUnknown(m)
}

var xxx_messageInfo_JSON_Array proto.InternalMessageInfo

func (m *JSON_Array) GetArray() []*JSON_Value {
	if m != nil {
		return m.Array
	}
	return nil
}

type JSON_Value struct {
	// Types that are valid to be assigned to Value:
	//	*JSON_Value_IsNull
	//	*JSON_Value_BooleanValue
	//	*JSON_Value_IsBoolean
	//	*JSON_Value_NumberValue
	//	*JSON_Value_IsNumber
	//	*JSON_Value_TextValue
	//	*JSON_Value_IsText
	//	*JSON_Value_ArrayValue
	//	*JSON_Value_IsArray
	//	*JSON_Value_ObjectValue
	//	*JSON_Value_IsObject
	Value                isJSON_Value_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *JSON_Value) Reset()         { *m = JSON_Value{} }
func (m *JSON_Value) String() string { return proto.CompactTextString(m) }
func (*JSON_Value) ProtoMessage()    {}
func (*JSON_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_62525685a9883c9a, []int{11, 2}
}
func (m *JSON_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSON_Value.Unmarshal(m, b)
}
func (m *JSON_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSON_Value.Marshal(b, m, deterministic)
}
func (dst *JSON_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSON_Value.Merge(dst, src)
}
func (m *JSON_Value) XXX_Size() int {
	return xxx_messageInfo_JSON_Value.Size(m)
}
func (m *JSON_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_JSON_Value.DiscardUnknown(m)
}

var xxx_messageInfo_JSON_Value proto.InternalMessageInfo

type isJSON_Value_Value interface {
	isJSON_Value_Value()
}

type JSON_Value_IsNull struct {
	IsNull bool `protobuf:"varint,1,opt,name=is_null,json=isNull,oneof"`
}
type JSON_Value_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,2,opt,name=boolean_value,json=booleanValue,oneof"`
}
type JSON_Value_IsBoolean struct {
	IsBoolean bool `protobuf:"varint,3,opt,name=is_boolean,json=isBoolean,oneof"`
}
type JSON_Value_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,4,opt,name=number_value,json=numberValue,oneof"`
}
type JSON_Value_IsNumber struct {
	IsNumber bool `protobuf:"varint,5,opt,name=is_number,json=isNumber,oneof"`
}
type JSON_Value_TextValue struct {
	TextValue string `protobuf:"bytes,6,opt,name=text_value,json=textValue,oneof"`
}
type JSON_Value_IsText struct {
	IsText bool `protobuf:"varint,7,opt,name=is_text,json=isText,oneof"`
}
type JSON_Value_ArrayValue struct {
	ArrayValue *JSON_Array `protobuf:"bytes,8,opt,name=array_value,json=arrayValue,oneof"`
}
type JSON_Value_IsArray struct {
	IsArray bool `protobuf:"varint,9,opt,name=is_array,json=isArray,oneof"`
}
type JSON_Value_ObjectValue struct {
	ObjectValue *JSON_Object `protobuf:"bytes,10,opt,name=object_value,json=objectValue,oneof"`
}
type JSON_Value_IsObject struct {
	IsObject bool `protobuf:"varint,11,opt,name=is_object,json=isObject,oneof"`
}

func (*JSON_Value_IsNull) isJSON_Value_Value()       {}
func (*JSON_Value_BooleanValue) isJSON_Value_Value() {}
func (*JSON_Value_IsBoolean) isJSON_Value_Value()    {}
func (*JSON_Value_NumberValue) isJSON_Value_Value()  {}
func (*JSON_Value_IsNumber) isJSON_Value_Value()     {}
func (*JSON_Value_TextValue) isJSON_Value_Value()    {}
func (*JSON_Value_IsText) isJSON_Value_Value()       {}
func (*JSON_Value_ArrayValue) isJSON_Value_Value()   {}
func (*JSON_Value_IsArray) isJSON_Value_Value()      {}
func (*JSON_Value_ObjectValue) isJSON_Value_Value()  {}
func (*JSON_Value_IsObject) isJSON_Value_Value()     {}

func (m *JSON_Value) GetValue() isJSON_Value_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *JSON_Value) GetIsNull() bool {
	if x, ok := m.GetValue().(*JSON_Value_IsNull); ok {
		return x.IsNull
	}
	return false
}

func (m *JSON_Value) GetBooleanValue() bool {
	if x, ok := m.GetValue().(*JSON_Value_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (m *JSON_Value) GetIsBoolean() bool {
	if x, ok := m.GetValue().(*JSON_Value_IsBoolean); ok {
		return x.IsBoolean
	}
	return false
}

func (m *JSON_Value) GetNumberValue() float64 {
	if x, ok := m.GetValue().(*JSON_Value_NumberValue); ok {
		return x.NumberValue
	}
	return 0
}

func (m *JSON_Value) GetIsNumber() bool {
	if x, ok := m.GetValue().(*JSON_Value_IsNumber); ok {
		return x.IsNumber
	}
	return false
}

func (m *JSON_Value) GetTextValue() string {
	if x, ok := m.GetValue().(*JSON_Value_TextValue); ok {
		return x.TextValue
	}
	return ""
}

func (m *JSON_Value) GetIsText() bool {
	if x, ok := m.GetValue().(*JSON_Value_IsText); ok {
		return x.IsText
	}
	return false
}

func (m *JSON_Value) GetArrayValue() *JSON_Array {
	if x, ok := m.GetValue().(*JSON_Value_ArrayValue); ok {
		return x.ArrayValue
	}
	return nil
}

func (m *JSON_Value) GetIsArray() bool {
	if x, ok := m.GetValue().(*JSON_Value_IsArray); ok {
		return x.IsArray
	}
	return false
}

func (m *JSON_Value) GetObjectValue() *JSON_Object {
	if x, ok := m.GetValue().(*JSON_Value_ObjectValue); ok {
		return x.ObjectValue
	}
	return nil
}

func (m *JSON_Value) GetIsObject() bool {
	if x, ok := m.GetValue().(*JSON_Value_IsObject); ok {
		return x.IsObject
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*JSON_Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _JSON_Value_OneofMarshaler, _JSON_Value_OneofUnmarshaler, _JSON_Value_OneofSizer, []interface{}{
		(*JSON_Value_IsNull)(nil),
		(*JSON_Value_BooleanValue)(nil),
		(*JSON_Value_IsBoolean)(nil),
		(*JSON_Value_NumberValue)(nil),
		(*JSON_Value_IsNumber)(nil),
		(*JSON_Value_TextValue)(nil),
		(*JSON_Value_IsText)(nil),
		(*JSON_Value_ArrayValue)(nil),
		(*JSON_Value_IsArray)(nil),
		(*JSON_Value_ObjectValue)(nil),
		(*JSON_Value_IsObject)(nil),
	}
}

func _JSON_Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*JSON_Value)
	// value
	switch x := m.Value.(type) {
	case *JSON_Value_IsNull:
		t := uint64(0)
		if x.IsNull {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *JSON_Value_BooleanValue:
		t := uint64(0)
		if x.BooleanValue {
			t = 1
		}
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *JSON_Value_IsBoolean:
		t := uint64(0)
		if x.IsBoolean {
			t = 1
		}
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *JSON_Value_NumberValue:
		b.EncodeVarint(4<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.NumberValue))
	case *JSON_Value_IsNumber:
		t := uint64(0)
		if x.IsNumber {
			t = 1
		}
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *JSON_Value_TextValue:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.TextValue)
	case *JSON_Value_IsText:
		t := uint64(0)
		if x.IsText {
			t = 1
		}
		b.EncodeVarint(7<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *JSON_Value_ArrayValue:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ArrayValue); err != nil {
			return err
		}
	case *JSON_Value_IsArray:
		t := uint64(0)
		if x.IsArray {
			t = 1
		}
		b.EncodeVarint(9<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *JSON_Value_ObjectValue:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ObjectValue); err != nil {
			return err
		}
	case *JSON_Value_IsObject:
		t := uint64(0)
		if x.IsObject {
			t = 1
		}
		b.EncodeVarint(11<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("JSON_Value.Value has unexpected type %T", x)
	}
	return nil
}

func _JSON_Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*JSON_Value)
	switch tag {
	case 1: // value.is_null
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &JSON_Value_IsNull{x != 0}
		return true, err
	case 2: // value.boolean_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &JSON_Value_BooleanValue{x != 0}
		return true, err
	case 3: // value.is_boolean
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &JSON_Value_IsBoolean{x != 0}
		return true, err
	case 4: // value.number_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &JSON_Value_NumberValue{math.Float64frombits(x)}
		return true, err
	case 5: // value.is_number
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &JSON_Value_IsNumber{x != 0}
		return true, err
	case 6: // value.text_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &JSON_Value_TextValue{x}
		return true, err
	case 7: // value.is_text
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &JSON_Value_IsText{x != 0}
		return true, err
	case 8: // value.array_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(JSON_Array)
		err := b.DecodeMessage(msg)
		m.Value = &JSON_Value_ArrayValue{msg}
		return true, err
	case 9: // value.is_array
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &JSON_Value_IsArray{x != 0}
		return true, err
	case 10: // value.object_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(JSON_Object)
		err := b.DecodeMessage(msg)
		m.Value = &JSON_Value_ObjectValue{msg}
		return true, err
	case 11: // value.is_object
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &JSON_Value_IsObject{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _JSON_Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*JSON_Value)
	// value
	switch x := m.Value.(type) {
	case *JSON_Value_IsNull:
		n += 1 // tag and wire
		n += 1
	case *JSON_Value_BooleanValue:
		n += 1 // tag and wire
		n += 1
	case *JSON_Value_IsBoolean:
		n += 1 // tag and wire
		n += 1
	case *JSON_Value_NumberValue:
		n += 1 // tag and wire
		n += 8
	case *JSON_Value_IsNumber:
		n += 1 // tag and wire
		n += 1
	case *JSON_Value_TextValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.TextValue)))
		n += len(x.TextValue)
	case *JSON_Value_IsText:
		n += 1 // tag and wire
		n += 1
	case *JSON_Value_ArrayValue:
		s := proto.Size(x.ArrayValue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *JSON_Value_IsArray:
		n += 1 // tag and wire
		n += 1
	case *JSON_Value_ObjectValue:
		s := proto.Size(x.ObjectValue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *JSON_Value_IsObject:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*YmlCfg)(nil), "main.YmlCfg")
	proto.RegisterType((*YmlCfg_Runtime)(nil), "main.YmlCfg.Runtime")
	proto.RegisterType((*YmlCfg_Exec)(nil), "main.YmlCfg.Exec")
	proto.RegisterType((*InitFuzzing)(nil), "main.InitFuzzing")
	proto.RegisterType((*SpecIR)(nil), "main.SpecIR")
	proto.RegisterType((*Schemas)(nil), "main.Schemas")
	proto.RegisterMapType((map[string]*Schema_JSONDraft05)(nil), "main.Schemas.SchemasJSONDraft05Entry")
	proto.RegisterType((*Endpoint)(nil), "main.Endpoint")
	proto.RegisterType((*EndpointJSONDraft05)(nil), "main.EndpointJSONDraft05")
	proto.RegisterMapType((map[uint32]*PtrOrSchemaJSONDraft05)(nil), "main.EndpointJSONDraft05.OutputsEntry")
	proto.RegisterType((*Path)(nil), "main.Path")
	proto.RegisterType((*Path_PathPartial)(nil), "main.Path.PathPartial")
	proto.RegisterType((*ParamsJSONDraft05)(nil), "main.ParamsJSONDraft05")
	proto.RegisterMapType((map[uint32]*ParamJSONDraft05)(nil), "main.ParamsJSONDraft05.BodyEntry")
	proto.RegisterMapType((map[uint32]*ParamJSONDraft05)(nil), "main.ParamsJSONDraft05.HeaderEntry")
	proto.RegisterMapType((map[uint32]*ParamJSONDraft05)(nil), "main.ParamsJSONDraft05.PathEntry")
	proto.RegisterMapType((map[uint32]*ParamJSONDraft05)(nil), "main.ParamsJSONDraft05.QueryEntry")
	proto.RegisterType((*ParamJSONDraft05)(nil), "main.ParamJSONDraft05")
	proto.RegisterType((*PtrOrSchemaJSONDraft05)(nil), "main.PtrOrSchemaJSONDraft05")
	proto.RegisterType((*Schema)(nil), "main.Schema")
	proto.RegisterType((*Schema_JSONDraft05)(nil), "main.Schema.JSONDraft05")
	proto.RegisterMapType((map[string]*PtrOrSchemaJSONDraft05)(nil), "main.Schema.JSONDraft05.PropertiesEntry")
	proto.RegisterType((*Schema_JSONDraft05_Type)(nil), "main.Schema.JSONDraft05.Type")
	proto.RegisterType((*Schema_JSONDraft05_AdditionalProperties)(nil), "main.Schema.JSONDraft05.AdditionalProperties")
	proto.RegisterType((*JSON)(nil), "main.JSON")
	proto.RegisterType((*JSON_Object)(nil), "main.JSON.Object")
	proto.RegisterMapType((map[string]*JSON_Value)(nil), "main.JSON.Object.ObjectEntry")
	proto.RegisterType((*JSON_Array)(nil), "main.JSON.Array")
	proto.RegisterType((*JSON_Value)(nil), "main.JSON.Value")
	proto.RegisterEnum("main.Method", Method_name, Method_value)
	proto.RegisterEnum("main.YmlCfg_Kind", YmlCfg_Kind_name, YmlCfg_Kind_value)
	proto.RegisterEnum("main.Schema_JSONDraft05_TypeType", Schema_JSONDraft05_TypeType_name, Schema_JSONDraft05_TypeType_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_62525685a9883c9a) }

var fileDescriptor_messages_62525685a9883c9a = []byte{
	// 1796 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xdd, 0x6e, 0x1b, 0xc7,
	0x15, 0x16, 0xc5, 0xe5, 0x92, 0x3c, 0x4b, 0x2a, 0xeb, 0xb1, 0x22, 0xaf, 0xe8, 0x38, 0x51, 0x18,
	0x3b, 0x15, 0x52, 0x97, 0x49, 0xe5, 0xba, 0x08, 0x52, 0x14, 0x08, 0x29, 0x33, 0xa6, 0x62, 0x99,
	0x64, 0x46, 0x54, 0x5a, 0xa3, 0x17, 0xc4, 0x48, 0x1c, 0x8a, 0x6b, 0xef, 0x9f, 0x77, 0x87, 0x2e,
	0x99, 0xa2, 0x6f, 0xd0, 0x47, 0xe8, 0x03, 0xf4, 0xb2, 0x6f, 0x50, 0xa0, 0x97, 0xbd, 0xef, 0x23,
	0xf4, 0x3d, 0x8a, 0x39, 0x33, 0x4b, 0x2e, 0x65, 0x12, 0x16, 0x02, 0xdf, 0x48, 0x33, 0xe7, 0x7c,
	0xdf, 0xf9, 0x9d, 0x99, 0xb3, 0x12, 0xec, 0xf8, 0x3c, 0x49, 0xd8, 0x15, 0x4f, 0x1a, 0x51, 0x1c,
	0x8a, 0x90, 0x18, 0x3e, 0x73, 0x83, 0xfa, 0x3f, 0xf3, 0x60, 0xbe, 0xf0, 0xbd, 0xe3, 0xf1, 0x15,
	0x71, 0xa0, 0xf8, 0x86, 0xc7, 0x89, 0x1b, 0x06, 0x4e, 0xee, 0x20, 0x77, 0x58, 0xa5, 0xe9, 0x96,
	0xdc, 0x03, 0x60, 0x53, 0x31, 0x19, 0x8a, 0xf0, 0x15, 0x0f, 0x9c, 0xed, 0x83, 0xdc, 0x61, 0x99,
	0x96, 0xa5, 0x64, 0x20, 0x05, 0xe4, 0x01, 0x18, 0xaf, 0xdc, 0x60, 0xe4, 0xe4, 0x0f, 0x72, 0x87,
	0x3b, 0x47, 0xb7, 0x1a, 0xd2, 0x70, 0x43, 0x19, 0x6d, 0x3c, 0x73, 0x83, 0x11, 0x45, 0x35, 0x21,
	0x60, 0x8c, 0x5d, 0x8f, 0x3b, 0x06, 0xf2, 0x71, 0x4d, 0x1a, 0x50, 0x8c, 0xa7, 0x81, 0x70, 0x7d,
	0xee, 0x14, 0x0e, 0x72, 0x87, 0xd6, 0xd1, 0xee, 0x0a, 0x9b, 0x2a, 0x1d, 0x4d, 0x41, 0xd2, 0x15,
	0x9f, 0xf1, 0x4b, 0xc7, 0x44, 0xf0, 0xaa, 0xab, 0xf6, 0x8c, 0x5f, 0x52, 0x54, 0xd7, 0x42, 0x28,
	0x6a, 0xaa, 0xf4, 0x3a, 0x09, 0x13, 0x81, 0x29, 0x95, 0x29, 0xae, 0xa5, 0x2c, 0x0a, 0x63, 0xa1,
	0x33, 0xc1, 0xb5, 0xcc, 0x71, 0xec, 0x06, 0xcc, 0x1b, 0x22, 0x3a, 0xaf, 0x72, 0x44, 0x49, 0x47,
	0x52, 0x16, 0x6a, 0x24, 0x1a, 0x19, 0x75, 0x3f, 0x8c, 0x45, 0xed, 0x3b, 0x30, 0xa4, 0x7b, 0xb2,
	0x0b, 0x85, 0x44, 0xb0, 0x58, 0xba, 0xcb, 0x1f, 0x96, 0xa9, 0xda, 0x48, 0x69, 0xcc, 0x13, 0x2e,
	0x1d, 0xa2, 0x14, 0x37, 0x32, 0x8a, 0x44, 0x84, 0x91, 0x93, 0x47, 0x21, 0xae, 0xeb, 0x75, 0x30,
	0x64, 0xc5, 0x88, 0x05, 0xc5, 0xf3, 0xee, 0xb3, 0x6e, 0xef, 0x0f, 0x5d, 0x7b, 0x8b, 0x54, 0xa1,
	0xdc, 0x8b, 0x78, 0xd0, 0xec, 0x9f, 0xbc, 0x79, 0x64, 0xe7, 0xea, 0xe7, 0x60, 0x9d, 0x04, 0xae,
	0xf8, 0x6e, 0xfa, 0xd3, 0x4f, 0x6e, 0x70, 0x45, 0xee, 0x83, 0x79, 0x19, 0x06, 0x63, 0xf7, 0x0a,
	0x53, 0xb4, 0x8e, 0x2a, 0xd9, 0xa2, 0x50, 0xad, 0x23, 0x07, 0x60, 0x24, 0x11, 0xbf, 0xc4, 0x94,
	0x17, 0x98, 0xb3, 0x88, 0x5f, 0x9e, 0x50, 0x8a, 0x9a, 0x7a, 0x02, 0xa6, 0xda, 0x63, 0x79, 0x44,
	0x9c, 0xe8, 0x1c, 0x70, 0x4d, 0x7e, 0x01, 0xc5, 0xe4, 0x72, 0xc2, 0x7d, 0x96, 0x68, 0x13, 0x55,
	0x6d, 0x42, 0x09, 0x69, 0xaa, 0x25, 0x0f, 0xa1, 0xcc, 0x83, 0x51, 0x14, 0xba, 0x81, 0x48, 0x30,
	0x35, 0xeb, 0x68, 0x47, 0x41, 0xdb, 0x5a, 0x4c, 0x97, 0x80, 0xfa, 0xbf, 0x73, 0x50, 0xd4, 0x26,
	0xc8, 0x8f, 0x70, 0x5b, 0x1b, 0x19, 0x7e, 0x7f, 0xd6, 0xeb, 0x3e, 0x89, 0xd9, 0x58, 0x7c, 0xf5,
	0x18, 0xa3, 0xb0, 0x8e, 0x1e, 0xac, 0xb8, 0x4b, 0x7f, 0x67, 0x70, 0xed, 0x40, 0xc4, 0x73, 0x4a,
	0x92, 0xb7, 0x14, 0xb5, 0x21, 0xdc, 0xd9, 0x00, 0x27, 0x36, 0xe4, 0x5f, 0xf1, 0xb9, 0x3e, 0x1b,
	0x72, 0x49, 0x1a, 0x50, 0x78, 0xc3, 0xbc, 0x29, 0xd7, 0x59, 0x3a, 0x59, 0xb7, 0x8d, 0x0c, 0x9f,
	0x2a, 0xd8, 0x37, 0xdb, 0x5f, 0xe7, 0xea, 0x63, 0x28, 0xa5, 0xb9, 0x91, 0x2e, 0xec, 0xa6, 0xd9,
	0x5d, 0xcb, 0x42, 0x9a, 0xdb, 0x5f, 0xad, 0x44, 0x06, 0xd0, 0xd9, 0xa2, 0xb7, 0xf9, 0xdb, 0xe2,
	0x16, 0x40, 0x29, 0x15, 0xd7, 0xff, 0xb1, 0x0d, 0xb7, 0xd7, 0x50, 0xe5, 0x09, 0xf0, 0xb9, 0x98,
	0x84, 0x23, 0xf4, 0xb2, 0x93, 0x76, 0xf7, 0x39, 0xca, 0xa8, 0xd6, 0x91, 0x8f, 0xc1, 0x88, 0x98,
	0x98, 0xe8, 0xc4, 0x40, 0x61, 0xfa, 0x4c, 0x4c, 0x28, 0xca, 0xc9, 0x97, 0x60, 0x46, 0x2c, 0x66,
	0x7e, 0x82, 0x87, 0xdf, 0x3a, 0xba, 0x93, 0x22, 0xa4, 0x2c, 0x9b, 0xb9, 0x86, 0x91, 0x6f, 0xa1,
	0x18, 0x4e, 0x45, 0x34, 0x15, 0x89, 0x63, 0x60, 0x8f, 0x3e, 0xdf, 0x98, 0x5d, 0xa3, 0xa7, 0x80,
	0xaa, 0x49, 0x29, 0xad, 0xf6, 0x47, 0xa8, 0x64, 0x15, 0xd9, 0x76, 0x54, 0x55, 0x3b, 0x8e, 0x56,
	0xdb, 0xf1, 0x91, 0x8e, 0x49, 0xc4, 0xbd, 0x58, 0xf5, 0x64, 0x43, 0x4b, 0xfe, 0x0c, 0x86, 0x4c,
	0x8d, 0x7c, 0x05, 0xc5, 0x88, 0xc5, 0xc2, 0x65, 0x9e, 0x3e, 0x47, 0x7b, 0xcb, 0xbc, 0xf1, 0x47,
	0x5f, 0x69, 0x69, 0x0a, 0xab, 0xfd, 0x1e, 0xac, 0x8c, 0x9c, 0xec, 0xca, 0xaa, 0xc5, 0xfa, 0xf9,
	0xe8, 0x6c, 0x51, 0xdc, 0x11, 0x02, 0xf9, 0x48, 0xc4, 0x18, 0x54, 0xb5, 0xb3, 0x45, 0xe5, 0xa6,
	0x65, 0xc0, 0x76, 0x14, 0xd5, 0xff, 0x65, 0xc0, 0xad, 0xb7, 0x4a, 0x46, 0x7e, 0x07, 0xe6, 0x84,
	0xb3, 0x11, 0x8f, 0x75, 0x14, 0x9f, 0x6d, 0xa8, 0x6d, 0xa3, 0x83, 0x28, 0x55, 0x26, 0x4d, 0x21,
	0x8f, 0x17, 0x8d, 0x93, 0xd4, 0x4f, 0x37, 0x51, 0x65, 0xd4, 0x8a, 0xa8, 0xfa, 0xf9, 0x18, 0x8c,
	0x8b, 0x70, 0x34, 0xd7, 0x77, 0x70, 0x23, 0xad, 0x15, 0x8e, 0xe6, 0x9a, 0x26, 0xe1, 0xe4, 0x6b,
	0x28, 0xbc, 0x9e, 0xf2, 0x78, 0xae, 0x7b, 0x5a, 0xdf, 0xc4, 0xfb, 0x41, 0x82, 0x14, 0x51, 0x11,
	0x6a, 0x3f, 0x80, 0x95, 0x09, 0x7f, 0x4d, 0x33, 0x1f, 0xae, 0x36, 0x73, 0x2f, 0x63, 0x7a, 0x7d,
	0x1b, 0x6b, 0x3d, 0x28, 0x2f, 0xd2, 0x7a, 0x5f, 0x06, 0x17, 0x09, 0xbf, 0x17, 0x83, 0x7d, 0x80,
	0x65, 0x25, 0xde, 0x87, 0xc5, 0x7a, 0x04, 0xf6, 0x75, 0x35, 0xf9, 0x16, 0xaa, 0xea, 0x61, 0x1b,
	0x86, 0xf1, 0x50, 0x9e, 0xbc, 0xdc, 0x0d, 0xae, 0x83, 0xa5, 0x28, 0xbd, 0xb8, 0x2f, 0x62, 0x52,
	0x83, 0x52, 0xcc, 0x5f, 0x4f, 0xdd, 0x98, 0x8f, 0x30, 0x94, 0x12, 0x5d, 0xec, 0xeb, 0x7f, 0x85,
	0xbd, 0xf5, 0x26, 0xd2, 0x73, 0x9e, 0xcb, 0x9c, 0x73, 0x72, 0x04, 0xa6, 0x32, 0xfc, 0xae, 0x27,
	0xb2, 0xb3, 0x45, 0x35, 0xb2, 0x75, 0x17, 0xf6, 0x23, 0x11, 0xcb, 0xe0, 0x75, 0x1a, 0x19, 0x58,
	0xfd, 0xbf, 0x15, 0x30, 0x15, 0xbb, 0xf6, 0x9f, 0x0a, 0x58, 0x59, 0xff, 0xbf, 0x06, 0x43, 0xcc,
	0x23, 0xae, 0x6f, 0xcd, 0xbd, 0x4d, 0x9e, 0x1a, 0x83, 0x79, 0xc4, 0x29, 0x42, 0xc9, 0x7d, 0x30,
	0x78, 0x30, 0xf5, 0x75, 0x70, 0xb6, 0xa2, 0x48, 0x6c, 0xa3, 0x19, 0xc7, 0x6c, 0x4e, 0x51, 0x4b,
	0xf6, 0xc0, 0x1c, 0x87, 0xb1, 0xcf, 0xd2, 0x49, 0xaf, 0x77, 0x72, 0xcc, 0xfb, 0x6e, 0x30, 0xf4,
	0x78, 0x70, 0x25, 0x26, 0x38, 0xe6, 0x0d, 0x5a, 0xf6, 0xdd, 0xe0, 0x14, 0x05, 0xa8, 0x66, 0xb3,
	0x54, 0x5d, 0xd0, 0x6a, 0x36, 0xd3, 0xea, 0xfb, 0xb0, 0x33, 0x61, 0xc9, 0x30, 0x03, 0x31, 0xb1,
	0xd4, 0x95, 0x09, 0x4b, 0x9e, 0x2f, 0x50, 0x8e, 0x7c, 0x93, 0x84, 0xe0, 0x71, 0xe0, 0x14, 0xd1,
	0x79, 0xba, 0x95, 0x1a, 0xdf, 0x0d, 0x5c, 0x7f, 0xea, 0x3b, 0xa5, 0x83, 0xdc, 0x61, 0x8e, 0xa6,
	0x5b, 0xd4, 0xb0, 0x19, 0x6a, 0xca, 0x5a, 0xa3, 0xb6, 0xe4, 0x13, 0xb0, 0xd0, 0xa7, 0xe6, 0x01,
	0x3a, 0x04, 0xe9, 0x50, 0x53, 0x53, 0x80, 0xa6, 0x5b, 0x4b, 0x80, 0xb6, 0xf0, 0x1b, 0xd8, 0x13,
	0x31, 0x0b, 0x12, 0x8f, 0x09, 0x3e, 0x1a, 0xfa, 0x53, 0x4f, 0xb8, 0x91, 0xc7, 0x87, 0xe1, 0xd8,
	0xa9, 0xa0, 0xab, 0xdd, 0xa5, 0xf6, 0xb9, 0x56, 0xf6, 0xc6, 0xe4, 0x97, 0x70, 0x8b, 0xcf, 0x2e,
	0xbd, 0x69, 0xe2, 0xbe, 0xe1, 0x0b, 0xef, 0x55, 0x34, 0x6e, 0x2f, 0x14, 0x69, 0x0c, 0xab, 0x60,
	0x1d, 0xc9, 0xce, 0x75, 0xb0, 0x8e, 0xe7, 0x08, 0x0a, 0xae, 0xe0, 0x7e, 0xe2, 0x7c, 0x80, 0x5d,
	0x7f, 0xc7, 0x9b, 0x8f, 0x50, 0xf2, 0x29, 0x54, 0xa6, 0x81, 0xfb, 0x7a, 0xca, 0x87, 0x8a, 0x6a,
	0xa3, 0x6d, 0x4b, 0xc9, 0x4e, 0x10, 0x72, 0x17, 0x64, 0x23, 0xb5, 0xfe, 0x16, 0xb6, 0xae, 0xe4,
	0xbb, 0xc1, 0x52, 0xc9, 0x66, 0x5a, 0x49, 0xb4, 0x92, 0xcd, 0x94, 0xb2, 0x0e, 0xd5, 0xb4, 0xad,
	0x0a, 0x70, 0x5b, 0x59, 0x57, 0x35, 0x54, 0x98, 0x0e, 0x40, 0x14, 0x87, 0x11, 0x8f, 0x85, 0xcb,
	0x13, 0x67, 0x17, 0x23, 0x3f, 0xdc, 0x78, 0x5e, 0xfb, 0x0b, 0xa8, 0x7a, 0x41, 0x33, 0xdc, 0x95,
	0x9b, 0xfa, 0x21, 0x7e, 0x81, 0x2d, 0xf6, 0xe4, 0x01, 0xec, 0xc8, 0x1c, 0x32, 0x9e, 0xf6, 0x30,
	0xd6, 0xaa, 0xef, 0x06, 0x4b, 0x9b, 0x08, 0x63, 0xb3, 0x2c, 0xec, 0x8e, 0x86, 0xb1, 0x59, 0x06,
	0xf6, 0x10, 0x48, 0x9a, 0x57, 0x06, 0xea, 0xa8, 0xb6, 0xa8, 0xe4, 0x32, 0xe8, 0x0b, 0xf8, 0x90,
	0x8d, 0x46, 0xae, 0x70, 0x43, 0xfc, 0x0c, 0x5e, 0x12, 0xf6, 0xf1, 0xa6, 0xfd, 0x6a, 0x63, 0xb2,
	0xcd, 0x05, 0x6b, 0x69, 0x8d, 0xee, 0xb2, 0x35, 0x52, 0xf2, 0x0d, 0xec, 0xcb, 0x88, 0xd6, 0xfb,
	0xa9, 0x61, 0x60, 0x77, 0x26, 0x2c, 0x59, 0x67, 0x91, 0x3c, 0x02, 0x93, 0x79, 0x9e, 0x3c, 0xb6,
	0x77, 0x6f, 0x72, 0x6e, 0x98, 0xe7, 0xf5, 0xc6, 0x48, 0x0a, 0xe6, 0x92, 0xf4, 0xd1, 0x8d, 0x48,
	0xc1, 0x5c, 0x91, 0xc2, 0x00, 0x2f, 0xc8, 0xbd, 0x9b, 0x90, 0xc2, 0x40, 0xde, 0x97, 0x2f, 0x20,
	0x1f, 0x84, 0xc2, 0xf9, 0xf8, 0x1d, 0x9f, 0x95, 0x12, 0x54, 0x7b, 0x09, 0x86, 0x7c, 0xd1, 0xea,
	0x17, 0xea, 0xf9, 0x23, 0x45, 0xc8, 0x37, 0xbb, 0x2f, 0xec, 0x2d, 0x52, 0x02, 0xa3, 0x7b, 0x7e,
	0x7a, 0x6a, 0xe7, 0xe4, 0x1f, 0x08, 0xad, 0x5e, 0xef, 0xb4, 0xdd, 0xec, 0xda, 0xdb, 0x72, 0x73,
	0xd2, 0x1d, 0xb4, 0x9f, 0xb6, 0xa9, 0x9d, 0x27, 0x00, 0x66, 0xf7, 0xfc, 0x79, 0xab, 0x4d, 0x6d,
	0x83, 0x94, 0xa1, 0xd0, 0xa4, 0xb4, 0xf9, 0xc2, 0x2e, 0x48, 0xf1, 0xd9, 0x80, 0x9e, 0x74, 0x9f,
	0xda, 0xa6, 0x5c, 0xf7, 0x5a, 0xdf, 0xb7, 0x8f, 0x07, 0x76, 0xb1, 0xf6, 0x27, 0xf8, 0xe0, 0xda,
	0x69, 0x5c, 0xf3, 0x55, 0xfc, 0x33, 0x3f, 0xc3, 0x6a, 0x7f, 0x81, 0xdd, 0xb5, 0xbd, 0x22, 0x90,
	0x9f, 0xb0, 0x04, 0x3d, 0x94, 0xe4, 0x5c, 0x99, 0xb0, 0x84, 0xb4, 0xae, 0xcf, 0xb8, 0x1b, 0xf8,
	0xea, 0x6c, 0xad, 0x4c, 0xb9, 0x96, 0x05, 0x65, 0x36, 0x1a, 0xe1, 0xa1, 0x49, 0xea, 0xff, 0x33,
	0xc0, 0x90, 0xd8, 0xda, 0xdf, 0x72, 0x60, 0xf6, 0x2e, 0x5e, 0xf2, 0x4b, 0x41, 0x1e, 0x83, 0x19,
	0xe2, 0x6a, 0x75, 0xa4, 0xe0, 0x7c, 0x50, 0x10, 0xfd, 0x4b, 0x7f, 0x82, 0x29, 0x70, 0xed, 0x19,
	0x58, 0x19, 0xf1, 0x9a, 0x02, 0x7d, 0xbe, 0x5a, 0xa0, 0xec, 0xd8, 0xf9, 0x51, 0xca, 0xb3, 0x45,
	0xf9, 0x12, 0x0a, 0x38, 0x8a, 0x24, 0x89, 0xc9, 0x85, 0x8e, 0x65, 0x0d, 0x09, 0xd5, 0xb5, 0xbf,
	0xe7, 0xa1, 0x80, 0x02, 0xb2, 0x0f, 0x45, 0x37, 0x19, 0x06, 0x53, 0xcf, 0x5b, 0xd4, 0xce, 0x74,
	0x93, 0xee, 0xd4, 0xf3, 0xc8, 0x03, 0xa8, 0x5e, 0x84, 0xa1, 0xc7, 0x59, 0x30, 0x5c, 0x46, 0x22,
	0x01, 0x15, 0x2d, 0x56, 0x16, 0x3e, 0x01, 0x70, 0x93, 0xa1, 0x16, 0xe1, 0xf0, 0x93, 0x98, 0xb2,
	0x9b, 0xb4, 0x94, 0x88, 0x7c, 0x06, 0x95, 0x60, 0xea, 0x5f, 0xf0, 0x58, 0x9b, 0x91, 0x33, 0x30,
	0x27, 0xeb, 0xac, 0xa4, 0xca, 0xca, 0x3d, 0x28, 0x63, 0x1c, 0x52, 0x82, 0x63, 0x50, 0x1a, 0x29,
	0xc9, 0x48, 0xa4, 0x44, 0x3a, 0x11, 0x7c, 0x26, 0xb4, 0x05, 0x53, 0x7f, 0x3a, 0x97, 0xa5, 0x2c,
	0x9b, 0x87, 0xdc, 0xe3, 0x08, 0xd4, 0x79, 0x0c, 0xf8, 0x4c, 0x90, 0x47, 0x60, 0x61, 0xd6, 0x9a,
	0x5c, 0x5a, 0x3f, 0xc6, 0x3b, 0x5b, 0x14, 0x10, 0xa6, 0xec, 0xdd, 0x85, 0x92, 0x9b, 0x0c, 0x55,
	0x31, 0xcb, 0xda, 0x60, 0xd1, 0x4d, 0x54, 0x99, 0x7f, 0x0b, 0x15, 0xd5, 0x46, 0x6d, 0x12, 0xb2,
	0xff, 0x3b, 0xc8, 0x74, 0x5e, 0x26, 0xa9, 0x80, 0xd9, 0x24, 0xf5, 0x71, 0xb1, 0x96, 0x49, 0x2a,
	0x74, 0xab, 0xa8, 0x5b, 0xfe, 0xc5, 0x4b, 0x30, 0xd5, 0x9f, 0x5a, 0xf2, 0x9e, 0x3e, 0x6d, 0x0f,
	0xd4, 0x3d, 0xed, 0xb4, 0x9b, 0x4f, 0xec, 0x9c, 0x5c, 0xf5, 0x7b, 0x67, 0x03, 0x7b, 0x5b, 0x2a,
	0xfb, 0xe7, 0x03, 0x3b, 0x2f, 0x2f, 0x65, 0xbf, 0x39, 0x38, 0xee, 0xd8, 0x86, 0xbc, 0x88, 0x4f,
	0xda, 0xa7, 0xed, 0x41, 0xdb, 0x2e, 0xc8, 0x4b, 0x7c, 0xdc, 0xeb, 0x76, 0xe5, 0xad, 0x34, 0xe5,
	0xa6, 0xd7, 0x1f, 0x9c, 0xf4, 0xba, 0x67, 0x76, 0x51, 0x12, 0x06, 0xb4, 0x79, 0xdc, 0xb6, 0x4b,
	0x17, 0x26, 0xfe, 0xef, 0xe6, 0xd1, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x68, 0x71, 0x72, 0x23,
	0xcd, 0x11, 0x00, 0x00,
}
