// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Method int32

const (
	Method_UNKNOWN Method = 0
	Method_GET     Method = 1
	Method_HEAD    Method = 2
	Method_POST    Method = 3
	Method_PUT     Method = 4
	Method_PATCH   Method = 5
	Method_DELETE  Method = 6
	Method_CONNECT Method = 7
	Method_OPTIONS Method = 8
	Method_TRACE   Method = 9
)

var Method_name = map[int32]string{
	0: "UNKNOWN",
	1: "GET",
	2: "HEAD",
	3: "POST",
	4: "PUT",
	5: "PATCH",
	6: "DELETE",
	7: "CONNECT",
	8: "OPTIONS",
	9: "TRACE",
}
var Method_value = map[string]int32{
	"UNKNOWN": 0,
	"GET":     1,
	"HEAD":    2,
	"POST":    3,
	"PUT":     4,
	"PATCH":   5,
	"DELETE":  6,
	"CONNECT": 7,
	"OPTIONS": 8,
	"TRACE":   9,
}

func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}
func (Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{0}
}

type UserCfg_Kind int32

const (
	UserCfg_UNKNOWN   UserCfg_Kind = 0
	UserCfg_OpenAPIv3 UserCfg_Kind = 1
)

var UserCfg_Kind_name = map[int32]string{
	0: "UNKNOWN",
	1: "OpenAPIv3",
}
var UserCfg_Kind_value = map[string]int32{
	"UNKNOWN":   0,
	"OpenAPIv3": 1,
}

func (x UserCfg_Kind) String() string {
	return proto.EnumName(UserCfg_Kind_name, int32(x))
}
func (UserCfg_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{0, 0}
}

type ParamJSON_Kind int32

const (
	ParamJSON_UNKNOWN ParamJSON_Kind = 0
	ParamJSON_body    ParamJSON_Kind = 1
	ParamJSON_path    ParamJSON_Kind = 2
	ParamJSON_query   ParamJSON_Kind = 3
	ParamJSON_header  ParamJSON_Kind = 4
	ParamJSON_cookie  ParamJSON_Kind = 5
)

var ParamJSON_Kind_name = map[int32]string{
	0: "UNKNOWN",
	1: "body",
	2: "path",
	3: "query",
	4: "header",
	5: "cookie",
}
var ParamJSON_Kind_value = map[string]int32{
	"UNKNOWN": 0,
	"body":    1,
	"path":    2,
	"query":   3,
	"header":  4,
	"cookie":  5,
}

func (x ParamJSON_Kind) String() string {
	return proto.EnumName(ParamJSON_Kind_name, int32(x))
}
func (ParamJSON_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{8, 0}
}

type Schema_JSON_Type int32

const (
	Schema_JSON_UNKNOWN Schema_JSON_Type = 0
	Schema_JSON_any     Schema_JSON_Type = 1
	Schema_JSON_null    Schema_JSON_Type = 2
	Schema_JSON_boolean Schema_JSON_Type = 3
	Schema_JSON_integer Schema_JSON_Type = 4
	Schema_JSON_number  Schema_JSON_Type = 5
	Schema_JSON_array   Schema_JSON_Type = 6
	Schema_JSON_string  Schema_JSON_Type = 7
	Schema_JSON_object  Schema_JSON_Type = 8
)

var Schema_JSON_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "any",
	2: "null",
	3: "boolean",
	4: "integer",
	5: "number",
	6: "array",
	7: "string",
	8: "object",
}
var Schema_JSON_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"any":     1,
	"null":    2,
	"boolean": 3,
	"integer": 4,
	"number":  5,
	"array":   6,
	"string":  7,
	"object":  8,
}

func (x Schema_JSON_Type) String() string {
	return proto.EnumName(Schema_JSON_Type_name, int32(x))
}
func (Schema_JSON_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{10, 0, 0}
}

// type: string
type Schema_JSON_Format int32

const (
	Schema_JSON_NONE      Schema_JSON_Format = 0
	Schema_JSON_date_time Schema_JSON_Format = 1
	Schema_JSON_date      Schema_JSON_Format = 2
	// time = 3;
	Schema_JSON_email Schema_JSON_Format = 4
	// idn-email = 5;
	Schema_JSON_hostname Schema_JSON_Format = 6
	// idn_hostname = 7;
	Schema_JSON_ipv4          Schema_JSON_Format = 8
	Schema_JSON_ipv6          Schema_JSON_Format = 9
	Schema_JSON_uri           Schema_JSON_Format = 10
	Schema_JSON_uri_reference Schema_JSON_Format = 11
	// iri = 12;
	// iri_reference = 13;
	// uri_template = 14;
	// json_pointer = 15;
	// relative_json_pointer = 16;
	Schema_JSON_regex    Schema_JSON_Format = 17
	Schema_JSON_int32    Schema_JSON_Format = 18
	Schema_JSON_int64    Schema_JSON_Format = 19
	Schema_JSON_float    Schema_JSON_Format = 20
	Schema_JSON_double   Schema_JSON_Format = 21
	Schema_JSON_byte     Schema_JSON_Format = 22
	Schema_JSON_binary   Schema_JSON_Format = 23
	Schema_JSON_password Schema_JSON_Format = 24
)

var Schema_JSON_Format_name = map[int32]string{
	0:  "NONE",
	1:  "date_time",
	2:  "date",
	4:  "email",
	6:  "hostname",
	8:  "ipv4",
	9:  "ipv6",
	10: "uri",
	11: "uri_reference",
	17: "regex",
	18: "int32",
	19: "int64",
	20: "float",
	21: "double",
	22: "byte",
	23: "binary",
	24: "password",
}
var Schema_JSON_Format_value = map[string]int32{
	"NONE":          0,
	"date_time":     1,
	"date":          2,
	"email":         4,
	"hostname":      6,
	"ipv4":          8,
	"ipv6":          9,
	"uri":           10,
	"uri_reference": 11,
	"regex":         17,
	"int32":         18,
	"int64":         19,
	"float":         20,
	"double":        21,
	"byte":          22,
	"binary":        23,
	"password":      24,
}

func (x Schema_JSON_Format) String() string {
	return proto.EnumName(Schema_JSON_Format_name, int32(x))
}
func (Schema_JSON_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{10, 0, 1}
}

type UserCfg struct {
	Version              uint32           `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	AuthToken            string           `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Seed                 []byte           `protobuf:"bytes,3,opt,name=seed,proto3" json:"seed,omitempty"`
	Kind                 UserCfg_Kind     `protobuf:"varint,4,opt,name=kind,proto3,enum=main.UserCfg_Kind" json:"kind,omitempty"`
	File                 string           `protobuf:"bytes,5,opt,name=file,proto3" json:"file,omitempty"`
	Runtime              *UserCfg_Runtime `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Exec                 *UserCfg_Exec    `protobuf:"bytes,7,opt,name=exec,proto3" json:"exec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserCfg) Reset()         { *m = UserCfg{} }
func (m *UserCfg) String() string { return proto.CompactTextString(m) }
func (*UserCfg) ProtoMessage()    {}
func (*UserCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{0}
}
func (m *UserCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCfg.Unmarshal(m, b)
}
func (m *UserCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCfg.Marshal(b, m, deterministic)
}
func (dst *UserCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCfg.Merge(dst, src)
}
func (m *UserCfg) XXX_Size() int {
	return xxx_messageInfo_UserCfg.Size(m)
}
func (m *UserCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCfg.DiscardUnknown(m)
}

var xxx_messageInfo_UserCfg proto.InternalMessageInfo

func (m *UserCfg) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UserCfg) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *UserCfg) GetSeed() []byte {
	if m != nil {
		return m.Seed
	}
	return nil
}

func (m *UserCfg) GetKind() UserCfg_Kind {
	if m != nil {
		return m.Kind
	}
	return UserCfg_UNKNOWN
}

func (m *UserCfg) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *UserCfg) GetRuntime() *UserCfg_Runtime {
	if m != nil {
		return m.Runtime
	}
	return nil
}

func (m *UserCfg) GetExec() *UserCfg_Exec {
	if m != nil {
		return m.Exec
	}
	return nil
}

type UserCfg_Runtime struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	FinalHost            string   `protobuf:"bytes,3,opt,name=final_host,json=finalHost,proto3" json:"final_host,omitempty"`
	FinalPort            string   `protobuf:"bytes,4,opt,name=final_port,json=finalPort,proto3" json:"final_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCfg_Runtime) Reset()         { *m = UserCfg_Runtime{} }
func (m *UserCfg_Runtime) String() string { return proto.CompactTextString(m) }
func (*UserCfg_Runtime) ProtoMessage()    {}
func (*UserCfg_Runtime) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{0, 0}
}
func (m *UserCfg_Runtime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCfg_Runtime.Unmarshal(m, b)
}
func (m *UserCfg_Runtime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCfg_Runtime.Marshal(b, m, deterministic)
}
func (dst *UserCfg_Runtime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCfg_Runtime.Merge(dst, src)
}
func (m *UserCfg_Runtime) XXX_Size() int {
	return xxx_messageInfo_UserCfg_Runtime.Size(m)
}
func (m *UserCfg_Runtime) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCfg_Runtime.DiscardUnknown(m)
}

var xxx_messageInfo_UserCfg_Runtime proto.InternalMessageInfo

func (m *UserCfg_Runtime) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *UserCfg_Runtime) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *UserCfg_Runtime) GetFinalHost() string {
	if m != nil {
		return m.FinalHost
	}
	return ""
}

func (m *UserCfg_Runtime) GetFinalPort() string {
	if m != nil {
		return m.FinalPort
	}
	return ""
}

type UserCfg_Exec struct {
	Start                []string `protobuf:"bytes,1,rep,name=start,proto3" json:"start,omitempty"`
	Reset_               []string `protobuf:"bytes,2,rep,name=reset,proto3" json:"reset,omitempty"`
	Stop                 []string `protobuf:"bytes,3,rep,name=stop,proto3" json:"stop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCfg_Exec) Reset()         { *m = UserCfg_Exec{} }
func (m *UserCfg_Exec) String() string { return proto.CompactTextString(m) }
func (*UserCfg_Exec) ProtoMessage()    {}
func (*UserCfg_Exec) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{0, 1}
}
func (m *UserCfg_Exec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCfg_Exec.Unmarshal(m, b)
}
func (m *UserCfg_Exec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCfg_Exec.Marshal(b, m, deterministic)
}
func (dst *UserCfg_Exec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCfg_Exec.Merge(dst, src)
}
func (m *UserCfg_Exec) XXX_Size() int {
	return xxx_messageInfo_UserCfg_Exec.Size(m)
}
func (m *UserCfg_Exec) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCfg_Exec.DiscardUnknown(m)
}

var xxx_messageInfo_UserCfg_Exec proto.InternalMessageInfo

func (m *UserCfg_Exec) GetStart() []string {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *UserCfg_Exec) GetReset_() []string {
	if m != nil {
		return m.Reset_
	}
	return nil
}

func (m *UserCfg_Exec) GetStop() []string {
	if m != nil {
		return m.Stop
	}
	return nil
}

type FuzzCfg struct {
	Cfg                  *UserCfg `protobuf:"bytes,1,opt,name=cfg,proto3" json:"cfg,omitempty"`
	Spec                 *SpecIR  `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FuzzCfg) Reset()         { *m = FuzzCfg{} }
func (m *FuzzCfg) String() string { return proto.CompactTextString(m) }
func (*FuzzCfg) ProtoMessage()    {}
func (*FuzzCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{1}
}
func (m *FuzzCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuzzCfg.Unmarshal(m, b)
}
func (m *FuzzCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuzzCfg.Marshal(b, m, deterministic)
}
func (dst *FuzzCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuzzCfg.Merge(dst, src)
}
func (m *FuzzCfg) XXX_Size() int {
	return xxx_messageInfo_FuzzCfg.Size(m)
}
func (m *FuzzCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_FuzzCfg.DiscardUnknown(m)
}

var xxx_messageInfo_FuzzCfg proto.InternalMessageInfo

func (m *FuzzCfg) GetCfg() *UserCfg {
	if m != nil {
		return m.Cfg
	}
	return nil
}

func (m *FuzzCfg) GetSpec() *SpecIR {
	if m != nil {
		return m.Spec
	}
	return nil
}

type SpecIR struct {
	Schemas              *Schemas    `protobuf:"bytes,1,opt,name=schemas,proto3" json:"schemas,omitempty"`
	Endpoints            []*Endpoint `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SpecIR) Reset()         { *m = SpecIR{} }
func (m *SpecIR) String() string { return proto.CompactTextString(m) }
func (*SpecIR) ProtoMessage()    {}
func (*SpecIR) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{2}
}
func (m *SpecIR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecIR.Unmarshal(m, b)
}
func (m *SpecIR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecIR.Marshal(b, m, deterministic)
}
func (dst *SpecIR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecIR.Merge(dst, src)
}
func (m *SpecIR) XXX_Size() int {
	return xxx_messageInfo_SpecIR.Size(m)
}
func (m *SpecIR) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecIR.DiscardUnknown(m)
}

var xxx_messageInfo_SpecIR proto.InternalMessageInfo

func (m *SpecIR) GetSchemas() *Schemas {
	if m != nil {
		return m.Schemas
	}
	return nil
}

func (m *SpecIR) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type Schemas struct {
	// All schemas are here. Only mention SchemaPtr everywhere else.
	// Start at 1. 0 (zero) is reserved for bug finding.
	Json                 map[uint32]*RefOrSchemaJSON `protobuf:"bytes,1,rep,name=json,proto3" json:"json,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Schemas) Reset()         { *m = Schemas{} }
func (m *Schemas) String() string { return proto.CompactTextString(m) }
func (*Schemas) ProtoMessage()    {}
func (*Schemas) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{3}
}
func (m *Schemas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schemas.Unmarshal(m, b)
}
func (m *Schemas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schemas.Marshal(b, m, deterministic)
}
func (dst *Schemas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schemas.Merge(dst, src)
}
func (m *Schemas) XXX_Size() int {
	return xxx_messageInfo_Schemas.Size(m)
}
func (m *Schemas) XXX_DiscardUnknown() {
	xxx_messageInfo_Schemas.DiscardUnknown(m)
}

var xxx_messageInfo_Schemas proto.InternalMessageInfo

func (m *Schemas) GetJson() map[uint32]*RefOrSchemaJSON {
	if m != nil {
		return m.Json
	}
	return nil
}

type RefOrSchemaJSON struct {
	// Types that are valid to be assigned to PtrOrSchema:
	//	*RefOrSchemaJSON_Ptr
	//	*RefOrSchemaJSON_Schema
	PtrOrSchema          isRefOrSchemaJSON_PtrOrSchema `protobuf_oneof:"ptr_or_schema"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *RefOrSchemaJSON) Reset()         { *m = RefOrSchemaJSON{} }
func (m *RefOrSchemaJSON) String() string { return proto.CompactTextString(m) }
func (*RefOrSchemaJSON) ProtoMessage()    {}
func (*RefOrSchemaJSON) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{4}
}
func (m *RefOrSchemaJSON) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefOrSchemaJSON.Unmarshal(m, b)
}
func (m *RefOrSchemaJSON) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefOrSchemaJSON.Marshal(b, m, deterministic)
}
func (dst *RefOrSchemaJSON) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefOrSchemaJSON.Merge(dst, src)
}
func (m *RefOrSchemaJSON) XXX_Size() int {
	return xxx_messageInfo_RefOrSchemaJSON.Size(m)
}
func (m *RefOrSchemaJSON) XXX_DiscardUnknown() {
	xxx_messageInfo_RefOrSchemaJSON.DiscardUnknown(m)
}

var xxx_messageInfo_RefOrSchemaJSON proto.InternalMessageInfo

type isRefOrSchemaJSON_PtrOrSchema interface {
	isRefOrSchemaJSON_PtrOrSchema()
}

type RefOrSchemaJSON_Ptr struct {
	Ptr *SchemaPtr `protobuf:"bytes,1,opt,name=ptr,proto3,oneof"`
}
type RefOrSchemaJSON_Schema struct {
	Schema *Schema_JSON `protobuf:"bytes,2,opt,name=schema,proto3,oneof"`
}

func (*RefOrSchemaJSON_Ptr) isRefOrSchemaJSON_PtrOrSchema()    {}
func (*RefOrSchemaJSON_Schema) isRefOrSchemaJSON_PtrOrSchema() {}

func (m *RefOrSchemaJSON) GetPtrOrSchema() isRefOrSchemaJSON_PtrOrSchema {
	if m != nil {
		return m.PtrOrSchema
	}
	return nil
}

func (m *RefOrSchemaJSON) GetPtr() *SchemaPtr {
	if x, ok := m.GetPtrOrSchema().(*RefOrSchemaJSON_Ptr); ok {
		return x.Ptr
	}
	return nil
}

func (m *RefOrSchemaJSON) GetSchema() *Schema_JSON {
	if x, ok := m.GetPtrOrSchema().(*RefOrSchemaJSON_Schema); ok {
		return x.Schema
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RefOrSchemaJSON) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RefOrSchemaJSON_OneofMarshaler, _RefOrSchemaJSON_OneofUnmarshaler, _RefOrSchemaJSON_OneofSizer, []interface{}{
		(*RefOrSchemaJSON_Ptr)(nil),
		(*RefOrSchemaJSON_Schema)(nil),
	}
}

func _RefOrSchemaJSON_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RefOrSchemaJSON)
	// ptr_or_schema
	switch x := m.PtrOrSchema.(type) {
	case *RefOrSchemaJSON_Ptr:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ptr); err != nil {
			return err
		}
	case *RefOrSchemaJSON_Schema:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Schema); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RefOrSchemaJSON.PtrOrSchema has unexpected type %T", x)
	}
	return nil
}

func _RefOrSchemaJSON_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RefOrSchemaJSON)
	switch tag {
	case 1: // ptr_or_schema.ptr
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SchemaPtr)
		err := b.DecodeMessage(msg)
		m.PtrOrSchema = &RefOrSchemaJSON_Ptr{msg}
		return true, err
	case 2: // ptr_or_schema.schema
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Schema_JSON)
		err := b.DecodeMessage(msg)
		m.PtrOrSchema = &RefOrSchemaJSON_Schema{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RefOrSchemaJSON_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RefOrSchemaJSON)
	// ptr_or_schema
	switch x := m.PtrOrSchema.(type) {
	case *RefOrSchemaJSON_Ptr:
		s := proto.Size(x.Ptr)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RefOrSchemaJSON_Schema:
		s := proto.Size(x.Schema)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SchemaPtr struct {
	// Pointer to actual schema. i.e. key in Schemas message.
	UID uint32 `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	// $ref if was ref'd, in canonical/absolute (#/...-like) format.
	Ref                  string   `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemaPtr) Reset()         { *m = SchemaPtr{} }
func (m *SchemaPtr) String() string { return proto.CompactTextString(m) }
func (*SchemaPtr) ProtoMessage()    {}
func (*SchemaPtr) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{5}
}
func (m *SchemaPtr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaPtr.Unmarshal(m, b)
}
func (m *SchemaPtr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaPtr.Marshal(b, m, deterministic)
}
func (dst *SchemaPtr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaPtr.Merge(dst, src)
}
func (m *SchemaPtr) XXX_Size() int {
	return xxx_messageInfo_SchemaPtr.Size(m)
}
func (m *SchemaPtr) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaPtr.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaPtr proto.InternalMessageInfo

func (m *SchemaPtr) GetUID() uint32 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *SchemaPtr) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

type Endpoint struct {
	// Types that are valid to be assigned to Endpoint:
	//	*Endpoint_Json
	Endpoint             isEndpoint_Endpoint `protobuf_oneof:"endpoint"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{6}
}
func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (dst *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(dst, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

type isEndpoint_Endpoint interface {
	isEndpoint_Endpoint()
}

type Endpoint_Json struct {
	Json *EndpointJSON `protobuf:"bytes,1,opt,name=json,proto3,oneof"`
}

func (*Endpoint_Json) isEndpoint_Endpoint() {}

func (m *Endpoint) GetEndpoint() isEndpoint_Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

func (m *Endpoint) GetJson() *EndpointJSON {
	if x, ok := m.GetEndpoint().(*Endpoint_Json); ok {
		return x.Json
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Endpoint) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Endpoint_OneofMarshaler, _Endpoint_OneofUnmarshaler, _Endpoint_OneofSizer, []interface{}{
		(*Endpoint_Json)(nil),
	}
}

func _Endpoint_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Endpoint)
	// endpoint
	switch x := m.Endpoint.(type) {
	case *Endpoint_Json:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Json); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Endpoint.Endpoint has unexpected type %T", x)
	}
	return nil
}

func _Endpoint_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Endpoint)
	switch tag {
	case 1: // endpoint.json
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EndpointJSON)
		err := b.DecodeMessage(msg)
		m.Endpoint = &Endpoint_Json{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Endpoint_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Endpoint)
	// endpoint
	switch x := m.Endpoint.(type) {
	case *Endpoint_Json:
		s := proto.Size(x.Json)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type EndpointJSON struct {
	Method       Method         `protobuf:"varint,1,opt,name=method,proto3,enum=main.Method" json:"method,omitempty"`
	PathPartials []*PathPartial `protobuf:"bytes,2,rep,name=path_partials,json=pathPartials,proto3" json:"path_partials,omitempty"`
	Inputs       []*ParamJSON   `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// The uint32 key replaces an enum of 1XX,...,201,204,...,5XX,XXX.
	Outputs              map[uint32]*SchemaPtr `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EndpointJSON) Reset()         { *m = EndpointJSON{} }
func (m *EndpointJSON) String() string { return proto.CompactTextString(m) }
func (*EndpointJSON) ProtoMessage()    {}
func (*EndpointJSON) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{7}
}
func (m *EndpointJSON) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointJSON.Unmarshal(m, b)
}
func (m *EndpointJSON) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointJSON.Marshal(b, m, deterministic)
}
func (dst *EndpointJSON) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointJSON.Merge(dst, src)
}
func (m *EndpointJSON) XXX_Size() int {
	return xxx_messageInfo_EndpointJSON.Size(m)
}
func (m *EndpointJSON) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointJSON.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointJSON proto.InternalMessageInfo

func (m *EndpointJSON) GetMethod() Method {
	if m != nil {
		return m.Method
	}
	return Method_UNKNOWN
}

func (m *EndpointJSON) GetPathPartials() []*PathPartial {
	if m != nil {
		return m.PathPartials
	}
	return nil
}

func (m *EndpointJSON) GetInputs() []*ParamJSON {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *EndpointJSON) GetOutputs() map[uint32]*SchemaPtr {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type ParamJSON struct {
	// Whether this param has to be present
	Required bool `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`
	// Pointer to Schemas message
	Ptr *SchemaPtr `protobuf:"bytes,2,opt,name=ptr,proto3" json:"ptr,omitempty"`
	// Note: bodies have an empty name
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Kind                 ParamJSON_Kind `protobuf:"varint,4,opt,name=kind,proto3,enum=main.ParamJSON_Kind" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ParamJSON) Reset()         { *m = ParamJSON{} }
func (m *ParamJSON) String() string { return proto.CompactTextString(m) }
func (*ParamJSON) ProtoMessage()    {}
func (*ParamJSON) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{8}
}
func (m *ParamJSON) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParamJSON.Unmarshal(m, b)
}
func (m *ParamJSON) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParamJSON.Marshal(b, m, deterministic)
}
func (dst *ParamJSON) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamJSON.Merge(dst, src)
}
func (m *ParamJSON) XXX_Size() int {
	return xxx_messageInfo_ParamJSON.Size(m)
}
func (m *ParamJSON) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamJSON.DiscardUnknown(m)
}

var xxx_messageInfo_ParamJSON proto.InternalMessageInfo

func (m *ParamJSON) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *ParamJSON) GetPtr() *SchemaPtr {
	if m != nil {
		return m.Ptr
	}
	return nil
}

func (m *ParamJSON) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ParamJSON) GetKind() ParamJSON_Kind {
	if m != nil {
		return m.Kind
	}
	return ParamJSON_UNKNOWN
}

type PathPartial struct {
	// Types that are valid to be assigned to Pp:
	//	*PathPartial_Part
	//	*PathPartial_Ptr
	Pp                   isPathPartial_Pp `protobuf_oneof:"pp"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PathPartial) Reset()         { *m = PathPartial{} }
func (m *PathPartial) String() string { return proto.CompactTextString(m) }
func (*PathPartial) ProtoMessage()    {}
func (*PathPartial) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{9}
}
func (m *PathPartial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathPartial.Unmarshal(m, b)
}
func (m *PathPartial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathPartial.Marshal(b, m, deterministic)
}
func (dst *PathPartial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathPartial.Merge(dst, src)
}
func (m *PathPartial) XXX_Size() int {
	return xxx_messageInfo_PathPartial.Size(m)
}
func (m *PathPartial) XXX_DiscardUnknown() {
	xxx_messageInfo_PathPartial.DiscardUnknown(m)
}

var xxx_messageInfo_PathPartial proto.InternalMessageInfo

type isPathPartial_Pp interface {
	isPathPartial_Pp()
}

type PathPartial_Part struct {
	Part string `protobuf:"bytes,1,opt,name=part,proto3,oneof"`
}
type PathPartial_Ptr struct {
	Ptr string `protobuf:"bytes,2,opt,name=ptr,proto3,oneof"`
}

func (*PathPartial_Part) isPathPartial_Pp() {}
func (*PathPartial_Ptr) isPathPartial_Pp()  {}

func (m *PathPartial) GetPp() isPathPartial_Pp {
	if m != nil {
		return m.Pp
	}
	return nil
}

func (m *PathPartial) GetPart() string {
	if x, ok := m.GetPp().(*PathPartial_Part); ok {
		return x.Part
	}
	return ""
}

func (m *PathPartial) GetPtr() string {
	if x, ok := m.GetPp().(*PathPartial_Ptr); ok {
		return x.Ptr
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PathPartial) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PathPartial_OneofMarshaler, _PathPartial_OneofUnmarshaler, _PathPartial_OneofSizer, []interface{}{
		(*PathPartial_Part)(nil),
		(*PathPartial_Ptr)(nil),
	}
}

func _PathPartial_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PathPartial)
	// pp
	switch x := m.Pp.(type) {
	case *PathPartial_Part:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Part)
	case *PathPartial_Ptr:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Ptr)
	case nil:
	default:
		return fmt.Errorf("PathPartial.Pp has unexpected type %T", x)
	}
	return nil
}

func _PathPartial_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PathPartial)
	switch tag {
	case 1: // pp.part
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Pp = &PathPartial_Part{x}
		return true, err
	case 2: // pp.ptr
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Pp = &PathPartial_Ptr{x}
		return true, err
	default:
		return false, nil
	}
}

func _PathPartial_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PathPartial)
	// pp
	switch x := m.Pp.(type) {
	case *PathPartial_Part:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Part)))
		n += len(x.Part)
	case *PathPartial_Ptr:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Ptr)))
		n += len(x.Ptr)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Schema struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schema) Reset()         { *m = Schema{} }
func (m *Schema) String() string { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()    {}
func (*Schema) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{10}
}
func (m *Schema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema.Unmarshal(m, b)
}
func (m *Schema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema.Marshal(b, m, deterministic)
}
func (dst *Schema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema.Merge(dst, src)
}
func (m *Schema) XXX_Size() int {
	return xxx_messageInfo_Schema.Size(m)
}
func (m *Schema) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema.DiscardUnknown(m)
}

var xxx_messageInfo_Schema proto.InternalMessageInfo

type Schema_JSON struct {
	Type         []Schema_JSON_Type `protobuf:"varint,1,rep,packed,name=type,proto3,enum=main.Schema_JSON_Type" json:"type,omitempty"`
	Enum         []*ValueJSON       `protobuf:"bytes,2,rep,name=enum,proto3" json:"enum,omitempty"`
	Format       Schema_JSON_Format `protobuf:"varint,3,opt,name=format,proto3,enum=main.Schema_JSON_Format" json:"format,omitempty"`
	MinLength    uint64             `protobuf:"varint,4,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	MaxLength    uint64             `protobuf:"varint,5,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	HasMaxLength bool               `protobuf:"varint,6,opt,name=has_max_length,json=hasMaxLength,proto3" json:"has_max_length,omitempty"`
	Pattern      string             `protobuf:"bytes,7,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// type: number | integer
	Minimum              float64 `protobuf:"fixed64,8,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Maximum              float64 `protobuf:"fixed64,9,opt,name=maximum,proto3" json:"maximum,omitempty"`
	HasMinimum           bool    `protobuf:"varint,10,opt,name=has_minimum,json=hasMinimum,proto3" json:"has_minimum,omitempty"`
	HasMaximum           bool    `protobuf:"varint,11,opt,name=has_maximum,json=hasMaximum,proto3" json:"has_maximum,omitempty"`
	TranslatedMultipleOf float64 `protobuf:"fixed64,12,opt,name=translated_multiple_of,json=translatedMultipleOf,proto3" json:"translated_multiple_of,omitempty"`
	ExclusiveMinimum     bool    `protobuf:"varint,13,opt,name=exclusive_minimum,json=exclusiveMinimum,proto3" json:"exclusive_minimum,omitempty"`
	ExclusiveMaximum     bool    `protobuf:"varint,14,opt,name=exclusive_maximum,json=exclusiveMaximum,proto3" json:"exclusive_maximum,omitempty"`
	// type: array
	Items       []*SchemaPtr `protobuf:"bytes,15,rep,name=items,proto3" json:"items,omitempty"`
	UniqueItems bool         `protobuf:"varint,16,opt,name=unique_items,json=uniqueItems,proto3" json:"unique_items,omitempty"`
	MinItems    uint64       `protobuf:"varint,17,opt,name=min_items,json=minItems,proto3" json:"min_items,omitempty"`
	MaxItems    uint64       `protobuf:"varint,18,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	HasMaxItems bool         `protobuf:"varint,19,opt,name=has_max_items,json=hasMaxItems,proto3" json:"has_max_items,omitempty"`
	// type: object
	Properties              map[string]*SchemaPtr             `protobuf:"bytes,20,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Required                []string                          `protobuf:"bytes,21,rep,name=required,proto3" json:"required,omitempty"`
	MinProperties           uint64                            `protobuf:"varint,22,opt,name=min_properties,json=minProperties,proto3" json:"min_properties,omitempty"`
	MaxProperties           uint64                            `protobuf:"varint,23,opt,name=max_properties,json=maxProperties,proto3" json:"max_properties,omitempty"`
	HasMaxProperties        bool                              `protobuf:"varint,24,opt,name=has_max_properties,json=hasMaxProperties,proto3" json:"has_max_properties,omitempty"`
	AdditionalProperties    *Schema_JSON_AdditionalProperties `protobuf:"bytes,25,opt,name=additional_properties,json=additionalProperties,proto3" json:"additional_properties,omitempty"`
	HasAdditionalProperties bool                              `protobuf:"varint,26,opt,name=has_additional_properties,json=hasAdditionalProperties,proto3" json:"has_additional_properties,omitempty"`
	AllOf                   []*SchemaPtr                      `protobuf:"bytes,27,rep,name=all_of,json=allOf,proto3" json:"all_of,omitempty"`
	AnyOf                   []*SchemaPtr                      `protobuf:"bytes,28,rep,name=any_of,json=anyOf,proto3" json:"any_of,omitempty"`
	OneOf                   []*SchemaPtr                      `protobuf:"bytes,29,rep,name=one_of,json=oneOf,proto3" json:"one_of,omitempty"`
	Not                     *SchemaPtr                        `protobuf:"bytes,30,opt,name=not,proto3" json:"not,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                          `json:"-"`
	XXX_unrecognized        []byte                            `json:"-"`
	XXX_sizecache           int32                             `json:"-"`
}

func (m *Schema_JSON) Reset()         { *m = Schema_JSON{} }
func (m *Schema_JSON) String() string { return proto.CompactTextString(m) }
func (*Schema_JSON) ProtoMessage()    {}
func (*Schema_JSON) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{10, 0}
}
func (m *Schema_JSON) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema_JSON.Unmarshal(m, b)
}
func (m *Schema_JSON) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema_JSON.Marshal(b, m, deterministic)
}
func (dst *Schema_JSON) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema_JSON.Merge(dst, src)
}
func (m *Schema_JSON) XXX_Size() int {
	return xxx_messageInfo_Schema_JSON.Size(m)
}
func (m *Schema_JSON) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema_JSON.DiscardUnknown(m)
}

var xxx_messageInfo_Schema_JSON proto.InternalMessageInfo

func (m *Schema_JSON) GetType() []Schema_JSON_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Schema_JSON) GetEnum() []*ValueJSON {
	if m != nil {
		return m.Enum
	}
	return nil
}

func (m *Schema_JSON) GetFormat() Schema_JSON_Format {
	if m != nil {
		return m.Format
	}
	return Schema_JSON_NONE
}

func (m *Schema_JSON) GetMinLength() uint64 {
	if m != nil {
		return m.MinLength
	}
	return 0
}

func (m *Schema_JSON) GetMaxLength() uint64 {
	if m != nil {
		return m.MaxLength
	}
	return 0
}

func (m *Schema_JSON) GetHasMaxLength() bool {
	if m != nil {
		return m.HasMaxLength
	}
	return false
}

func (m *Schema_JSON) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *Schema_JSON) GetMinimum() float64 {
	if m != nil {
		return m.Minimum
	}
	return 0
}

func (m *Schema_JSON) GetMaximum() float64 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

func (m *Schema_JSON) GetHasMinimum() bool {
	if m != nil {
		return m.HasMinimum
	}
	return false
}

func (m *Schema_JSON) GetHasMaximum() bool {
	if m != nil {
		return m.HasMaximum
	}
	return false
}

func (m *Schema_JSON) GetTranslatedMultipleOf() float64 {
	if m != nil {
		return m.TranslatedMultipleOf
	}
	return 0
}

func (m *Schema_JSON) GetExclusiveMinimum() bool {
	if m != nil {
		return m.ExclusiveMinimum
	}
	return false
}

func (m *Schema_JSON) GetExclusiveMaximum() bool {
	if m != nil {
		return m.ExclusiveMaximum
	}
	return false
}

func (m *Schema_JSON) GetItems() []*SchemaPtr {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Schema_JSON) GetUniqueItems() bool {
	if m != nil {
		return m.UniqueItems
	}
	return false
}

func (m *Schema_JSON) GetMinItems() uint64 {
	if m != nil {
		return m.MinItems
	}
	return 0
}

func (m *Schema_JSON) GetMaxItems() uint64 {
	if m != nil {
		return m.MaxItems
	}
	return 0
}

func (m *Schema_JSON) GetHasMaxItems() bool {
	if m != nil {
		return m.HasMaxItems
	}
	return false
}

func (m *Schema_JSON) GetProperties() map[string]*SchemaPtr {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Schema_JSON) GetRequired() []string {
	if m != nil {
		return m.Required
	}
	return nil
}

func (m *Schema_JSON) GetMinProperties() uint64 {
	if m != nil {
		return m.MinProperties
	}
	return 0
}

func (m *Schema_JSON) GetMaxProperties() uint64 {
	if m != nil {
		return m.MaxProperties
	}
	return 0
}

func (m *Schema_JSON) GetHasMaxProperties() bool {
	if m != nil {
		return m.HasMaxProperties
	}
	return false
}

func (m *Schema_JSON) GetAdditionalProperties() *Schema_JSON_AdditionalProperties {
	if m != nil {
		return m.AdditionalProperties
	}
	return nil
}

func (m *Schema_JSON) GetHasAdditionalProperties() bool {
	if m != nil {
		return m.HasAdditionalProperties
	}
	return false
}

func (m *Schema_JSON) GetAllOf() []*SchemaPtr {
	if m != nil {
		return m.AllOf
	}
	return nil
}

func (m *Schema_JSON) GetAnyOf() []*SchemaPtr {
	if m != nil {
		return m.AnyOf
	}
	return nil
}

func (m *Schema_JSON) GetOneOf() []*SchemaPtr {
	if m != nil {
		return m.OneOf
	}
	return nil
}

func (m *Schema_JSON) GetNot() *SchemaPtr {
	if m != nil {
		return m.Not
	}
	return nil
}

// /FIXME true is equivalent to {}, false is equivalent to {"not": {}}
type Schema_JSON_AdditionalProperties struct {
	// Types that are valid to be assigned to AddProps:
	//	*Schema_JSON_AdditionalProperties_AlwaysSucceed
	//	*Schema_JSON_AdditionalProperties_Ref
	AddProps             isSchema_JSON_AdditionalProperties_AddProps `protobuf_oneof:"add_props"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *Schema_JSON_AdditionalProperties) Reset()         { *m = Schema_JSON_AdditionalProperties{} }
func (m *Schema_JSON_AdditionalProperties) String() string { return proto.CompactTextString(m) }
func (*Schema_JSON_AdditionalProperties) ProtoMessage()    {}
func (*Schema_JSON_AdditionalProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{10, 0, 1}
}
func (m *Schema_JSON_AdditionalProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema_JSON_AdditionalProperties.Unmarshal(m, b)
}
func (m *Schema_JSON_AdditionalProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema_JSON_AdditionalProperties.Marshal(b, m, deterministic)
}
func (dst *Schema_JSON_AdditionalProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema_JSON_AdditionalProperties.Merge(dst, src)
}
func (m *Schema_JSON_AdditionalProperties) XXX_Size() int {
	return xxx_messageInfo_Schema_JSON_AdditionalProperties.Size(m)
}
func (m *Schema_JSON_AdditionalProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema_JSON_AdditionalProperties.DiscardUnknown(m)
}

var xxx_messageInfo_Schema_JSON_AdditionalProperties proto.InternalMessageInfo

type isSchema_JSON_AdditionalProperties_AddProps interface {
	isSchema_JSON_AdditionalProperties_AddProps()
}

type Schema_JSON_AdditionalProperties_AlwaysSucceed struct {
	AlwaysSucceed bool `protobuf:"varint,1,opt,name=always_succeed,json=alwaysSucceed,proto3,oneof"`
}
type Schema_JSON_AdditionalProperties_Ref struct {
	Ref *SchemaPtr `protobuf:"bytes,2,opt,name=ref,proto3,oneof"`
}

func (*Schema_JSON_AdditionalProperties_AlwaysSucceed) isSchema_JSON_AdditionalProperties_AddProps() {}
func (*Schema_JSON_AdditionalProperties_Ref) isSchema_JSON_AdditionalProperties_AddProps()           {}

func (m *Schema_JSON_AdditionalProperties) GetAddProps() isSchema_JSON_AdditionalProperties_AddProps {
	if m != nil {
		return m.AddProps
	}
	return nil
}

func (m *Schema_JSON_AdditionalProperties) GetAlwaysSucceed() bool {
	if x, ok := m.GetAddProps().(*Schema_JSON_AdditionalProperties_AlwaysSucceed); ok {
		return x.AlwaysSucceed
	}
	return false
}

func (m *Schema_JSON_AdditionalProperties) GetRef() *SchemaPtr {
	if x, ok := m.GetAddProps().(*Schema_JSON_AdditionalProperties_Ref); ok {
		return x.Ref
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Schema_JSON_AdditionalProperties) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Schema_JSON_AdditionalProperties_OneofMarshaler, _Schema_JSON_AdditionalProperties_OneofUnmarshaler, _Schema_JSON_AdditionalProperties_OneofSizer, []interface{}{
		(*Schema_JSON_AdditionalProperties_AlwaysSucceed)(nil),
		(*Schema_JSON_AdditionalProperties_Ref)(nil),
	}
}

func _Schema_JSON_AdditionalProperties_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Schema_JSON_AdditionalProperties)
	// add_props
	switch x := m.AddProps.(type) {
	case *Schema_JSON_AdditionalProperties_AlwaysSucceed:
		t := uint64(0)
		if x.AlwaysSucceed {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Schema_JSON_AdditionalProperties_Ref:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ref); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Schema_JSON_AdditionalProperties.AddProps has unexpected type %T", x)
	}
	return nil
}

func _Schema_JSON_AdditionalProperties_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Schema_JSON_AdditionalProperties)
	switch tag {
	case 1: // add_props.always_succeed
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.AddProps = &Schema_JSON_AdditionalProperties_AlwaysSucceed{x != 0}
		return true, err
	case 2: // add_props.ref
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SchemaPtr)
		err := b.DecodeMessage(msg)
		m.AddProps = &Schema_JSON_AdditionalProperties_Ref{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Schema_JSON_AdditionalProperties_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Schema_JSON_AdditionalProperties)
	// add_props
	switch x := m.AddProps.(type) {
	case *Schema_JSON_AdditionalProperties_AlwaysSucceed:
		n += 1 // tag and wire
		n += 1
	case *Schema_JSON_AdditionalProperties_Ref:
		s := proto.Size(x.Ref)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ArrayJSON struct {
	Value                []*ValueJSON `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ArrayJSON) Reset()         { *m = ArrayJSON{} }
func (m *ArrayJSON) String() string { return proto.CompactTextString(m) }
func (*ArrayJSON) ProtoMessage()    {}
func (*ArrayJSON) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{11}
}
func (m *ArrayJSON) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayJSON.Unmarshal(m, b)
}
func (m *ArrayJSON) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayJSON.Marshal(b, m, deterministic)
}
func (dst *ArrayJSON) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayJSON.Merge(dst, src)
}
func (m *ArrayJSON) XXX_Size() int {
	return xxx_messageInfo_ArrayJSON.Size(m)
}
func (m *ArrayJSON) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayJSON.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayJSON proto.InternalMessageInfo

func (m *ArrayJSON) GetValue() []*ValueJSON {
	if m != nil {
		return m.Value
	}
	return nil
}

type ObjectJSON struct {
	Values               map[string]*ValueJSON `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ObjectJSON) Reset()         { *m = ObjectJSON{} }
func (m *ObjectJSON) String() string { return proto.CompactTextString(m) }
func (*ObjectJSON) ProtoMessage()    {}
func (*ObjectJSON) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{12}
}
func (m *ObjectJSON) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectJSON.Unmarshal(m, b)
}
func (m *ObjectJSON) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectJSON.Marshal(b, m, deterministic)
}
func (dst *ObjectJSON) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectJSON.Merge(dst, src)
}
func (m *ObjectJSON) XXX_Size() int {
	return xxx_messageInfo_ObjectJSON.Size(m)
}
func (m *ObjectJSON) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectJSON.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectJSON proto.InternalMessageInfo

func (m *ObjectJSON) GetValues() map[string]*ValueJSON {
	if m != nil {
		return m.Values
	}
	return nil
}

type ValueJSON struct {
	// Types that are valid to be assigned to Value:
	//	*ValueJSON_IsNull
	//	*ValueJSON_Boolean
	//	*ValueJSON_Number
	//	*ValueJSON_Text
	//	*ValueJSON_Array
	//	*ValueJSON_Object
	Value                isValueJSON_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ValueJSON) Reset()         { *m = ValueJSON{} }
func (m *ValueJSON) String() string { return proto.CompactTextString(m) }
func (*ValueJSON) ProtoMessage()    {}
func (*ValueJSON) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_093db647017d86a5, []int{13}
}
func (m *ValueJSON) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueJSON.Unmarshal(m, b)
}
func (m *ValueJSON) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueJSON.Marshal(b, m, deterministic)
}
func (dst *ValueJSON) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueJSON.Merge(dst, src)
}
func (m *ValueJSON) XXX_Size() int {
	return xxx_messageInfo_ValueJSON.Size(m)
}
func (m *ValueJSON) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueJSON.DiscardUnknown(m)
}

var xxx_messageInfo_ValueJSON proto.InternalMessageInfo

type isValueJSON_Value interface {
	isValueJSON_Value()
}

type ValueJSON_IsNull struct {
	IsNull bool `protobuf:"varint,1,opt,name=is_null,json=isNull,proto3,oneof"`
}
type ValueJSON_Boolean struct {
	Boolean bool `protobuf:"varint,2,opt,name=boolean,proto3,oneof"`
}
type ValueJSON_Number struct {
	Number float64 `protobuf:"fixed64,3,opt,name=number,proto3,oneof"`
}
type ValueJSON_Text struct {
	Text string `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}
type ValueJSON_Array struct {
	Array *ArrayJSON `protobuf:"bytes,5,opt,name=array,proto3,oneof"`
}
type ValueJSON_Object struct {
	Object *ObjectJSON `protobuf:"bytes,6,opt,name=object,proto3,oneof"`
}

func (*ValueJSON_IsNull) isValueJSON_Value()  {}
func (*ValueJSON_Boolean) isValueJSON_Value() {}
func (*ValueJSON_Number) isValueJSON_Value()  {}
func (*ValueJSON_Text) isValueJSON_Value()    {}
func (*ValueJSON_Array) isValueJSON_Value()   {}
func (*ValueJSON_Object) isValueJSON_Value()  {}

func (m *ValueJSON) GetValue() isValueJSON_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ValueJSON) GetIsNull() bool {
	if x, ok := m.GetValue().(*ValueJSON_IsNull); ok {
		return x.IsNull
	}
	return false
}

func (m *ValueJSON) GetBoolean() bool {
	if x, ok := m.GetValue().(*ValueJSON_Boolean); ok {
		return x.Boolean
	}
	return false
}

func (m *ValueJSON) GetNumber() float64 {
	if x, ok := m.GetValue().(*ValueJSON_Number); ok {
		return x.Number
	}
	return 0
}

func (m *ValueJSON) GetText() string {
	if x, ok := m.GetValue().(*ValueJSON_Text); ok {
		return x.Text
	}
	return ""
}

func (m *ValueJSON) GetArray() *ArrayJSON {
	if x, ok := m.GetValue().(*ValueJSON_Array); ok {
		return x.Array
	}
	return nil
}

func (m *ValueJSON) GetObject() *ObjectJSON {
	if x, ok := m.GetValue().(*ValueJSON_Object); ok {
		return x.Object
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ValueJSON) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ValueJSON_OneofMarshaler, _ValueJSON_OneofUnmarshaler, _ValueJSON_OneofSizer, []interface{}{
		(*ValueJSON_IsNull)(nil),
		(*ValueJSON_Boolean)(nil),
		(*ValueJSON_Number)(nil),
		(*ValueJSON_Text)(nil),
		(*ValueJSON_Array)(nil),
		(*ValueJSON_Object)(nil),
	}
}

func _ValueJSON_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ValueJSON)
	// value
	switch x := m.Value.(type) {
	case *ValueJSON_IsNull:
		t := uint64(0)
		if x.IsNull {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *ValueJSON_Boolean:
		t := uint64(0)
		if x.Boolean {
			t = 1
		}
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *ValueJSON_Number:
		b.EncodeVarint(3<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.Number))
	case *ValueJSON_Text:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Text)
	case *ValueJSON_Array:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Array); err != nil {
			return err
		}
	case *ValueJSON_Object:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Object); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ValueJSON.Value has unexpected type %T", x)
	}
	return nil
}

func _ValueJSON_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ValueJSON)
	switch tag {
	case 1: // value.is_null
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &ValueJSON_IsNull{x != 0}
		return true, err
	case 2: // value.boolean
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &ValueJSON_Boolean{x != 0}
		return true, err
	case 3: // value.number
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &ValueJSON_Number{math.Float64frombits(x)}
		return true, err
	case 4: // value.text
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &ValueJSON_Text{x}
		return true, err
	case 5: // value.array
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ArrayJSON)
		err := b.DecodeMessage(msg)
		m.Value = &ValueJSON_Array{msg}
		return true, err
	case 6: // value.object
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ObjectJSON)
		err := b.DecodeMessage(msg)
		m.Value = &ValueJSON_Object{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ValueJSON_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ValueJSON)
	// value
	switch x := m.Value.(type) {
	case *ValueJSON_IsNull:
		n += 1 // tag and wire
		n += 1
	case *ValueJSON_Boolean:
		n += 1 // tag and wire
		n += 1
	case *ValueJSON_Number:
		n += 1 // tag and wire
		n += 8
	case *ValueJSON_Text:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Text)))
		n += len(x.Text)
	case *ValueJSON_Array:
		s := proto.Size(x.Array)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ValueJSON_Object:
		s := proto.Size(x.Object)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*UserCfg)(nil), "main.UserCfg")
	proto.RegisterType((*UserCfg_Runtime)(nil), "main.UserCfg.Runtime")
	proto.RegisterType((*UserCfg_Exec)(nil), "main.UserCfg.Exec")
	proto.RegisterType((*FuzzCfg)(nil), "main.FuzzCfg")
	proto.RegisterType((*SpecIR)(nil), "main.SpecIR")
	proto.RegisterType((*Schemas)(nil), "main.Schemas")
	proto.RegisterMapType((map[uint32]*RefOrSchemaJSON)(nil), "main.Schemas.JsonEntry")
	proto.RegisterType((*RefOrSchemaJSON)(nil), "main.RefOrSchemaJSON")
	proto.RegisterType((*SchemaPtr)(nil), "main.SchemaPtr")
	proto.RegisterType((*Endpoint)(nil), "main.Endpoint")
	proto.RegisterType((*EndpointJSON)(nil), "main.EndpointJSON")
	proto.RegisterMapType((map[uint32]*SchemaPtr)(nil), "main.EndpointJSON.OutputsEntry")
	proto.RegisterType((*ParamJSON)(nil), "main.ParamJSON")
	proto.RegisterType((*PathPartial)(nil), "main.PathPartial")
	proto.RegisterType((*Schema)(nil), "main.Schema")
	proto.RegisterType((*Schema_JSON)(nil), "main.Schema.JSON")
	proto.RegisterMapType((map[string]*SchemaPtr)(nil), "main.Schema.JSON.PropertiesEntry")
	proto.RegisterType((*Schema_JSON_AdditionalProperties)(nil), "main.Schema.JSON.AdditionalProperties")
	proto.RegisterType((*ArrayJSON)(nil), "main.ArrayJSON")
	proto.RegisterType((*ObjectJSON)(nil), "main.ObjectJSON")
	proto.RegisterMapType((map[string]*ValueJSON)(nil), "main.ObjectJSON.ValuesEntry")
	proto.RegisterType((*ValueJSON)(nil), "main.ValueJSON")
	proto.RegisterEnum("main.Method", Method_name, Method_value)
	proto.RegisterEnum("main.UserCfg_Kind", UserCfg_Kind_name, UserCfg_Kind_value)
	proto.RegisterEnum("main.ParamJSON_Kind", ParamJSON_Kind_name, ParamJSON_Kind_value)
	proto.RegisterEnum("main.Schema_JSON_Type", Schema_JSON_Type_name, Schema_JSON_Type_value)
	proto.RegisterEnum("main.Schema_JSON_Format", Schema_JSON_Format_name, Schema_JSON_Format_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_093db647017d86a5) }

var fileDescriptor_messages_093db647017d86a5 = []byte{
	// 1743 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xcd, 0x6e, 0x1b, 0xc9,
	0x11, 0x16, 0xc5, 0x11, 0xc9, 0x29, 0x8a, 0x54, 0xab, 0x57, 0xb6, 0xc7, 0xdc, 0xdd, 0x58, 0xe6,
	0xae, 0x6d, 0xc1, 0x5e, 0x68, 0x03, 0xda, 0x30, 0x92, 0x05, 0x02, 0x44, 0x92, 0xe9, 0x48, 0xfe,
	0x21, 0x89, 0x11, 0x95, 0x1c, 0x72, 0x20, 0x5a, 0x64, 0x53, 0x9c, 0xf5, 0x4c, 0xcf, 0xb8, 0xa7,
	0x47, 0x26, 0xf7, 0x01, 0x72, 0xcc, 0x1b, 0xe4, 0x7d, 0x02, 0xe4, 0xb2, 0x87, 0x20, 0xcf, 0x13,
	0x54, 0x77, 0x0f, 0x39, 0xfa, 0x03, 0x92, 0x5b, 0x75, 0x7d, 0x5f, 0x55, 0x75, 0xfd, 0xb0, 0x6b,
	0x08, 0xcd, 0x88, 0xa7, 0x29, 0xbb, 0xe0, 0xe9, 0x7e, 0x22, 0x63, 0x15, 0x53, 0x27, 0x62, 0x81,
	0x68, 0xff, 0xb3, 0x0c, 0xd5, 0xb3, 0x94, 0xcb, 0xa3, 0xe9, 0x05, 0xf5, 0xa0, 0x7a, 0xc9, 0x65,
	0x1a, 0xc4, 0xc2, 0x2b, 0xed, 0x96, 0xf6, 0x1a, 0x7e, 0x7e, 0xa4, 0xdf, 0x02, 0xb0, 0x4c, 0xcd,
	0x46, 0x2a, 0xfe, 0xc4, 0x85, 0xb7, 0xbe, 0x5b, 0xda, 0x73, 0x7d, 0x17, 0x35, 0x43, 0x54, 0x50,
	0x0a, 0x4e, 0xca, 0xf9, 0xc4, 0x2b, 0xef, 0x96, 0xf6, 0x36, 0x7d, 0x2d, 0xd3, 0xa7, 0xe0, 0x7c,
	0x0a, 0xc4, 0xc4, 0x73, 0x76, 0x4b, 0x7b, 0xcd, 0x0e, 0xdd, 0xc7, 0x68, 0xfb, 0x36, 0xd2, 0xfe,
	0xfb, 0x40, 0x4c, 0x7c, 0x8d, 0xa3, 0xed, 0x34, 0x08, 0xb9, 0xb7, 0xa1, 0x9d, 0x6a, 0x99, 0xfe,
	0x08, 0x55, 0x99, 0x09, 0x15, 0x44, 0xdc, 0xab, 0xec, 0x96, 0xf6, 0xea, 0x9d, 0x7b, 0x57, 0xcd,
	0x7d, 0x03, 0xfa, 0x39, 0x0b, 0x83, 0xf1, 0x39, 0x1f, 0x7b, 0x55, 0xcd, 0xbe, 0x16, 0xac, 0x3b,
	0xe7, 0x63, 0x5f, 0xe3, 0xad, 0x18, 0xaa, 0xd6, 0x16, 0xe3, 0xce, 0xe2, 0x54, 0xe9, 0x4c, 0x5d,
	0x5f, 0xcb, 0xa8, 0x4b, 0x62, 0xa9, 0x6c, 0x82, 0x5a, 0xc6, 0xd4, 0xa7, 0x81, 0x60, 0xe1, 0x48,
	0xb3, 0xcb, 0x26, 0x75, 0xad, 0x39, 0x46, 0x93, 0x25, 0xac, 0x0d, 0x9d, 0x02, 0x3c, 0x88, 0xa5,
	0x6a, 0xbd, 0x05, 0x07, 0xc3, 0xd3, 0x1d, 0xd8, 0x48, 0x15, 0x93, 0x18, 0xae, 0xbc, 0xe7, 0xfa,
	0xe6, 0x80, 0x5a, 0xc9, 0x53, 0x8e, 0x01, 0xb5, 0x56, 0x1f, 0x74, 0x35, 0x55, 0x9c, 0x78, 0x65,
	0xad, 0xd4, 0x72, 0xbb, 0x0d, 0x0e, 0xd6, 0x8c, 0xd6, 0xa1, 0x7a, 0xd6, 0x7b, 0xdf, 0xeb, 0xff,
	0xa5, 0x47, 0xd6, 0x68, 0x03, 0xdc, 0x7e, 0xc2, 0xc5, 0xc1, 0xe0, 0xe4, 0xf2, 0x25, 0x29, 0xb5,
	0x3f, 0x40, 0xf5, 0x6d, 0xf6, 0xcb, 0x2f, 0xd8, 0xc9, 0x47, 0x50, 0x1e, 0x4f, 0x2f, 0x74, 0x6e,
	0xf5, 0x4e, 0xe3, 0x4a, 0x39, 0x7c, 0x44, 0xe8, 0x2e, 0x38, 0x69, 0xc2, 0xc7, 0x3a, 0xd3, 0x7a,
	0x67, 0xd3, 0x30, 0x4e, 0x13, 0x3e, 0x3e, 0xf1, 0x7d, 0x8d, 0xb4, 0x47, 0x50, 0x31, 0x67, 0xfa,
	0x0c, 0xaa, 0xe9, 0x78, 0xc6, 0x23, 0x96, 0x5e, 0x75, 0x78, 0x6a, 0x94, 0x7e, 0x8e, 0xd2, 0x1f,
	0xc0, 0xe5, 0x62, 0x92, 0xc4, 0x81, 0x50, 0xa9, 0x4e, 0xa9, 0xde, 0x69, 0x1a, 0x6a, 0xd7, 0xaa,
	0xfd, 0x15, 0xa1, 0xfd, 0xb7, 0x12, 0x54, 0xad, 0x0b, 0xfa, 0x02, 0x9c, 0x9f, 0x53, 0x3d, 0x76,
	0x68, 0xf4, 0xe0, 0x8a, 0xff, 0xfd, 0x77, 0x69, 0x2c, 0xba, 0x42, 0xc9, 0x85, 0xaf, 0x49, 0xad,
	0x1e, 0xb8, 0x4b, 0x15, 0x25, 0x50, 0xfe, 0xc4, 0x17, 0x76, 0x5e, 0x51, 0xa4, 0x2f, 0x60, 0xe3,
	0x92, 0x85, 0x19, 0xb7, 0xb9, 0xd9, 0xd1, 0xf1, 0xf9, 0xb4, 0x2f, 0x8d, 0xc7, 0x77, 0xa7, 0xfd,
	0x9e, 0x6f, 0x38, 0x3f, 0xad, 0xff, 0xae, 0xd4, 0x56, 0xb0, 0x75, 0x0d, 0xa5, 0xdf, 0x41, 0x39,
	0x51, 0xd2, 0xa6, 0xbb, 0x55, 0xbc, 0xce, 0x40, 0xc9, 0xe3, 0x35, 0x1f, 0x51, 0xfa, 0x02, 0x2a,
	0x26, 0x73, 0x1b, 0x69, 0xbb, 0xc8, 0xdb, 0x47, 0x3f, 0xc7, 0x6b, 0xbe, 0xa5, 0x1c, 0x6e, 0x41,
	0x23, 0x51, 0x72, 0x14, 0xcb, 0x91, 0x51, 0xb4, 0x7f, 0x04, 0x77, 0xe9, 0x11, 0xb3, 0x38, 0x3b,
	0x79, 0x93, 0x67, 0x71, 0x76, 0xf2, 0x06, 0x35, 0x92, 0x4f, 0xed, 0x24, 0xa2, 0xd8, 0xfe, 0x23,
	0xd4, 0xf2, 0x32, 0xd2, 0xbd, 0x65, 0xbd, 0x0a, 0xf3, 0x9e, 0xa3, 0x36, 0xb2, 0x66, 0x1c, 0x02,
	0xd4, 0xf2, 0x92, 0xb7, 0xff, 0xb1, 0x0e, 0x9b, 0x45, 0x12, 0xfd, 0x1e, 0x2a, 0x11, 0x57, 0xb3,
	0x78, 0xa2, 0x1d, 0x35, 0xf3, 0x39, 0xf8, 0xa8, 0x75, 0xbe, 0xc5, 0xe8, 0x6b, 0x68, 0x24, 0x4c,
	0xcd, 0x46, 0x09, 0x93, 0x2a, 0x60, 0x61, 0xde, 0x5a, 0x9b, 0xee, 0x80, 0xa9, 0xd9, 0xc0, 0x20,
	0xfe, 0x66, 0xb2, 0x3a, 0xa4, 0xf4, 0x19, 0x54, 0x02, 0x91, 0x64, 0x2a, 0xd5, 0x93, 0xbc, 0xac,
	0xe3, 0x80, 0x49, 0x16, 0xe9, 0x1e, 0x58, 0x98, 0xfe, 0x1e, 0xaa, 0x71, 0xa6, 0x34, 0xd3, 0xd1,
	0xcc, 0x47, 0x37, 0x13, 0xda, 0xef, 0x1b, 0x86, 0x19, 0x84, 0x9c, 0xdf, 0x7a, 0x0f, 0x9b, 0x45,
	0xe0, 0x96, 0x71, 0x78, 0x72, 0x75, 0x1c, 0xae, 0x37, 0xb3, 0x38, 0x08, 0xff, 0x2e, 0x81, 0xbb,
	0xbc, 0x1d, 0x6d, 0x41, 0x4d, 0xf2, 0xcf, 0x59, 0x20, 0xb9, 0x29, 0x4f, 0xcd, 0x5f, 0x9e, 0xe9,
	0x63, 0x33, 0x1f, 0x77, 0xb8, 0xd4, 0xd3, 0x41, 0xc1, 0x11, 0x2c, 0xe2, 0xf6, 0xc5, 0xd0, 0x32,
	0xb6, 0xad, 0xf0, 0x26, 0xee, 0x5c, 0xab, 0x47, 0xe1, 0x55, 0x6c, 0xbf, 0xbb, 0xed, 0xf7, 0x5e,
	0x03, 0xe7, 0x3c, 0x9e, 0x2c, 0x48, 0x09, 0x25, 0x2c, 0x35, 0x59, 0xa7, 0x2e, 0x6c, 0x7c, 0xce,
	0xb8, 0x5c, 0x90, 0x32, 0x05, 0xa8, 0xcc, 0x38, 0x9b, 0x70, 0x49, 0x1c, 0x94, 0xc7, 0x71, 0xfc,
	0x29, 0xe0, 0x64, 0xa3, 0xfd, 0x07, 0xa8, 0x17, 0x9a, 0x44, 0x77, 0xd0, 0x56, 0xda, 0x87, 0x0f,
	0xe7, 0x04, 0x4f, 0x94, 0xae, 0x32, 0x72, 0xed, 0x80, 0x1f, 0x3a, 0xb0, 0x9e, 0x24, 0xed, 0xff,
	0x34, 0xa0, 0x62, 0x72, 0x6b, 0xfd, 0xab, 0x01, 0x8e, 0xae, 0xcd, 0x73, 0x70, 0xd4, 0x22, 0xe1,
	0xfa, 0xf7, 0xda, 0xec, 0xdc, 0xbf, 0x31, 0xf8, 0xfb, 0xc3, 0x45, 0xc2, 0x7d, 0xcd, 0xa1, 0xdf,
	0x81, 0xc3, 0x45, 0x16, 0xd9, 0xa9, 0xb1, 0xc5, 0xfa, 0x33, 0x16, 0x5d, 0x0f, 0x81, 0x06, 0xe9,
	0x6f, 0xa1, 0x32, 0x8d, 0x65, 0xc4, 0xcc, 0x0b, 0xdb, 0xec, 0x78, 0x37, 0x5d, 0xbe, 0xd5, 0xb8,
	0x6f, 0x79, 0xf8, 0xf0, 0x46, 0x81, 0x18, 0x85, 0x5c, 0x5c, 0xa8, 0x99, 0xae, 0xa8, 0xe3, 0xbb,
	0x51, 0x20, 0x3e, 0x68, 0x85, 0x86, 0xd9, 0x3c, 0x87, 0x37, 0x2c, 0xcc, 0xe6, 0x16, 0xfe, 0x1e,
	0x9a, 0x33, 0x96, 0x8e, 0x0a, 0x94, 0x8a, 0x6e, 0xf1, 0xe6, 0x8c, 0xa5, 0x1f, 0x97, 0x2c, 0x0f,
	0xaa, 0x09, 0x53, 0x8a, 0x4b, 0xa1, 0x37, 0x8b, 0xeb, 0xe7, 0x47, 0x44, 0xa2, 0x40, 0x04, 0x51,
	0x16, 0x79, 0xb5, 0xdd, 0xd2, 0x5e, 0xc9, 0xcf, 0x8f, 0x1a, 0x61, 0x73, 0x8d, 0xb8, 0x16, 0x31,
	0x47, 0xfa, 0x08, 0xea, 0x3a, 0xa6, 0xb5, 0x03, 0x1d, 0x10, 0x30, 0xa0, 0x35, 0xcd, 0x09, 0xd6,
	0xbc, 0xbe, 0x22, 0x58, 0x0f, 0xaf, 0xe0, 0xbe, 0x92, 0x4c, 0xa4, 0x21, 0x53, 0x7c, 0x32, 0x8a,
	0xb2, 0x50, 0x05, 0x49, 0xc8, 0x47, 0xf1, 0xd4, 0xdb, 0xd4, 0xa1, 0x76, 0x56, 0xe8, 0x47, 0x0b,
	0xf6, 0xa7, 0xf4, 0x05, 0x6c, 0xf3, 0xf9, 0x38, 0xcc, 0xd2, 0xe0, 0x92, 0x2f, 0xa3, 0x37, 0xb4,
	0x73, 0xb2, 0x04, 0xf2, 0x3b, 0x5c, 0x25, 0xdb, 0x9b, 0x34, 0xaf, 0x93, 0xed, 0x7d, 0x9e, 0xc0,
	0x46, 0xa0, 0x78, 0x94, 0x7a, 0x5b, 0xc5, 0xde, 0x16, 0x7e, 0x5b, 0x1a, 0xa5, 0x8f, 0x61, 0x33,
	0x13, 0xc1, 0xe7, 0x8c, 0x8f, 0x0c, 0x9b, 0x68, 0x77, 0x75, 0xa3, 0x3b, 0xd1, 0x94, 0xaf, 0x01,
	0x7b, 0x67, 0xf1, 0x6d, 0xdd, 0xad, 0x5a, 0x14, 0x88, 0x15, 0xc8, 0xe6, 0x16, 0xa4, 0x16, 0x64,
	0x73, 0x03, 0xb6, 0xa1, 0x91, 0x77, 0xd2, 0x10, 0xbe, 0x32, 0xde, 0x4d, 0xd9, 0x0c, 0xe7, 0x00,
	0x20, 0x91, 0x71, 0xc2, 0xa5, 0x0a, 0x78, 0xea, 0xed, 0xe8, 0xcb, 0x3e, 0xbe, 0x39, 0x61, 0x83,
	0x25, 0xc7, 0xbc, 0x32, 0x05, 0xa3, 0x2b, 0xaf, 0xc1, 0x3d, 0xbd, 0x98, 0x57, 0xaf, 0xc1, 0x13,
	0x68, 0xe2, 0xe5, 0x0b, 0x21, 0xee, 0xeb, 0x4b, 0x36, 0xa2, 0x40, 0xac, 0x7c, 0x6a, 0x1a, 0x9b,
	0x17, 0x69, 0x0f, 0x2c, 0x8d, 0xcd, 0x0b, 0xb4, 0x1f, 0x80, 0xe6, 0x09, 0x15, 0xa8, 0x9e, 0x69,
	0x81, 0xc9, 0xaa, 0xc0, 0xfe, 0x2b, 0xdc, 0x63, 0x93, 0x49, 0xa0, 0x82, 0x58, 0x7f, 0x84, 0xac,
	0x0c, 0x1e, 0xea, 0xb7, 0xe9, 0xe9, 0xcd, 0x2c, 0x0f, 0x96, 0xf4, 0x95, 0x1b, 0x7f, 0x87, 0xdd,
	0xa2, 0xa5, 0x3f, 0xc1, 0x43, 0xbc, 0xca, 0xed, 0x01, 0x5a, 0xfa, 0x46, 0x0f, 0x66, 0x2c, 0xbd,
	0xcd, 0x23, 0x7d, 0x0a, 0x15, 0x16, 0x86, 0x38, 0x9b, 0x5f, 0xdf, 0x31, 0x1c, 0x2c, 0x0c, 0xfb,
	0x53, 0xcd, 0x13, 0x0b, 0xe4, 0x7d, 0x73, 0x17, 0x4f, 0x2c, 0x0c, 0x2f, 0x16, 0x7a, 0xd6, 0xbf,
	0xbd, 0x83, 0x17, 0x0b, 0x9c, 0xf6, 0xc7, 0x50, 0x16, 0xb1, 0xf2, 0x7e, 0x73, 0xc7, 0xd3, 0x2c,
	0x62, 0xd5, 0xea, 0xc1, 0xd6, 0xb5, 0x56, 0x17, 0xf7, 0x86, 0xfb, 0xff, 0xee, 0x8d, 0xd6, 0x67,
	0xd8, 0xb9, 0xb5, 0x04, 0xcf, 0xa0, 0xc9, 0xc2, 0x2f, 0x6c, 0x91, 0x8e, 0xd2, 0x6c, 0x3c, 0xe6,
	0xf9, 0x1e, 0x39, 0x5e, 0xf3, 0x1b, 0x46, 0x7f, 0x6a, 0xd4, 0xf8, 0xb9, 0x91, 0x2f, 0xfb, 0xdb,
	0x3f, 0x37, 0x24, 0x9f, 0x1e, 0xd6, 0xc1, 0x65, 0x93, 0x89, 0xee, 0x40, 0xda, 0x8e, 0xc1, 0xc1,
	0x27, 0xf6, 0xea, 0x7e, 0xa8, 0x42, 0x99, 0x09, 0xbb, 0x1e, 0x44, 0x16, 0x86, 0x64, 0x1d, 0xf1,
	0xf3, 0x38, 0x0e, 0x39, 0x13, 0xa4, 0x8c, 0x87, 0x40, 0x28, 0x7e, 0x91, 0x6f, 0x08, 0x91, 0x45,
	0xe7, 0x5c, 0x92, 0x0d, 0x5c, 0x22, 0x4c, 0x4a, 0xb6, 0x20, 0x15, 0x54, 0xa7, 0x4a, 0x06, 0xe2,
	0x82, 0x54, 0x51, 0x8e, 0xcf, 0x7f, 0xe6, 0x63, 0x45, 0x6a, 0xed, 0x5f, 0x4b, 0x50, 0x31, 0x2f,
	0x30, 0x7a, 0xef, 0xf5, 0x7b, 0x5d, 0xf3, 0x01, 0x3a, 0x61, 0x8a, 0x8f, 0xf0, 0x83, 0xda, 0x84,
	0xc5, 0xa3, 0xd9, 0x4a, 0x3c, 0x62, 0x41, 0x48, 0x1c, 0xba, 0x09, 0x35, 0xfc, 0x72, 0xc6, 0xfd,
	0x47, 0x2a, 0x48, 0x09, 0x92, 0xcb, 0x57, 0xa4, 0x66, 0xa5, 0xd7, 0xc4, 0xc5, 0x6b, 0x67, 0x32,
	0x20, 0x40, 0xb7, 0xa1, 0x91, 0xc9, 0x60, 0x24, 0xf9, 0x94, 0x4b, 0x2e, 0xc6, 0x9c, 0xd4, 0xd1,
	0x91, 0xe4, 0x17, 0x7c, 0x4e, 0xb6, 0x51, 0x0c, 0x84, 0x7a, 0xd9, 0x21, 0xd4, 0x8a, 0xaf, 0x5f,
	0x91, 0xaf, 0x50, 0x9c, 0x86, 0x31, 0x53, 0x64, 0x07, 0xaf, 0x3b, 0x89, 0xb3, 0xf3, 0x90, 0x93,
	0x7b, 0x7a, 0x55, 0x2e, 0x14, 0x27, 0xf7, 0x51, 0x7b, 0x1e, 0x08, 0x26, 0x17, 0xe4, 0x01, 0xde,
	0x25, 0x61, 0x69, 0xfa, 0x25, 0x96, 0x13, 0xe2, 0xb5, 0x3b, 0xe0, 0x1e, 0x60, 0xd6, 0x7a, 0xa3,
	0x2d, 0xdb, 0x5d, 0xba, 0x7d, 0x4d, 0x19, 0xb4, 0xfd, 0xf7, 0x12, 0x40, 0x5f, 0xd7, 0x44, 0x5b,
	0xbd, 0x82, 0x8a, 0xd6, 0xa7, 0xd6, 0xec, 0x1b, 0x63, 0xb6, 0x62, 0x18, 0x0f, 0xf6, 0x3d, 0xb1,
	0xdc, 0xd6, 0x3b, 0xa8, 0x17, 0xd4, 0xff, 0xf3, 0xec, 0x5d, 0xbf, 0x8c, 0xfe, 0x66, 0xf9, 0xb5,
	0x04, 0xee, 0x12, 0xa0, 0x0f, 0xa1, 0x1a, 0xa4, 0x23, 0xec, 0xfd, 0x72, 0xd4, 0x2a, 0x41, 0xda,
	0xcb, 0xc2, 0x90, 0xb6, 0x96, 0x93, 0xa0, 0xbd, 0x22, 0x94, 0x2b, 0xa8, 0x97, 0xcf, 0x82, 0xde,
	0xbe, 0x25, 0xb4, 0x32, 0x67, 0xfc, 0x58, 0x50, 0x7c, 0x6e, 0xff, 0xd8, 0xe0, 0xc7, 0x02, 0x9e,
	0xe8, 0x33, 0x3b, 0x2f, 0x7a, 0xaf, 0x2e, 0xef, 0xb7, 0x2c, 0xe6, 0xf1, 0x9a, 0x6f, 0x70, 0xfa,
	0x3c, 0x9f, 0x20, 0xfb, 0x3f, 0x8e, 0x5c, 0xaf, 0x0f, 0x86, 0x32, 0x8c, 0xc3, 0xaa, 0x4d, 0xfa,
	0xf9, 0x17, 0xa8, 0x98, 0x2f, 0xd0, 0x1b, 0xd3, 0xfd, 0xa7, 0xee, 0xd0, 0x8c, 0xd9, 0x71, 0xf7,
	0xe0, 0x0d, 0x59, 0x47, 0x69, 0xd0, 0x3f, 0x1d, 0x92, 0x32, 0x82, 0x83, 0xb3, 0x21, 0x71, 0x70,
	0x1e, 0x06, 0x07, 0xc3, 0xa3, 0x63, 0xb2, 0x81, 0x9d, 0x7f, 0xd3, 0xfd, 0xd0, 0x1d, 0x76, 0x49,
	0x05, 0x3d, 0x1d, 0xf5, 0x7b, 0xbd, 0xee, 0xd1, 0x90, 0x54, 0xf1, 0xd0, 0x1f, 0x0c, 0x4f, 0xfa,
	0xbd, 0x53, 0x52, 0x43, 0x83, 0xa1, 0x7f, 0x70, 0xd4, 0x25, 0xee, 0x79, 0x45, 0xff, 0x31, 0x7e,
	0xf9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x25, 0xf0, 0xe6, 0x2a, 0x0f, 0x00, 0x00,
}
