name: master

on:
  push: {}

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
    - name: Set lowercase image name
      run: echo IMAGE=ghcr.io/${SLUG,,} >>$GITHUB_ENV
      env:
        SLUG: ${{ github.repository }}

    - uses: actions/checkout@v3

    - name: Set TAG
      run: grep -F . Tagfile && echo TAG=$(cat Tagfile) >>$GITHUB_ENV

    - uses: docker/setup-buildx-action@v3.7.1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/bake-action@v3.1.0
      with:
        files: ./docker-bake.hcl
        targets: goreleaser-dist
        # TODO: cache-to
        # set: |
        #   *.cache-to=type=registry,ref=${{ env.IMAGE }}:goreleaser-dist,mode=max

    # TODO: cache-to
    # - name: If on master push image to GHCR
    #   run: docker push ${{ env.IMAGE }}:goreleaser-dist

    - name: Test CLI
      run: |
        tar zxvf ./dist/monkey-Linux-x86_64.tar.gz -C .
        ./monkey -h | grep monkey
        ./monkey help | grep monkey
        ./monkey version
        ./monkey fmt
        [[ $(./monkey version | wc -l) = 1 ]]
        ./monkey version | grep -F $(cat Tagfile)
        ./monkey --version | grep -F $(cat Tagfile)

    - uses: ncipollo/release-action@v1.13.0
      if: github.ref == 'refs/heads/master'
      with:
        artifacts: ./dist/*
        commit: master       # Required to push tag
        tag: ${{ env.TAG }}  # Required to push tag
        token: ${{ secrets.GITHUB_TOKEN }}
