name: shellcheck

on:
  push:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
# TODO - godownloader -r FuzzyMonkeyCo/monkey -o .godownloader.sh .goreleaser.yml
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        check_together: 'yes'
        severity: error
