name: shellcheck

on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
# TODO - godownloader -r FuzzyMonkeyCo/monkey -o .godownloader.sh .goreleaser.yml
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@1.1.0
      with:
        check_together: 'yes'
        severity: error
